<template>
  <div class="character">
    <b-container>
      <h1>{{ titlePrefix }} Character</h1>

      <div v-if="errors.length" class="text-danger field-validation-error mt-3">
        <ul>
          <li v-for="error in errors" v-bind:key="error">{{ error }}</li>
        </ul>
      </div>

      <div v-if="id === 'create' && createEnabled" class="mb-2 mt-2">
        <p>Create a new character. You can either fill out the character sheet manually or use the generator below.</p>

        <b-card title="Generate Level 1 Character">
          <p>Fill out character sheet automatically by randomly generating a level 1 character.</p>
          <b-collapse id="generation-1-details" class="mt-2" :visible="genLvl1Details">
            <p>
              The generation process follows all steps from character chapter of the rulebook. This includes all random
              tables such as "Random Species Table". For example, the probability of generating a High Elf is only 1%.
            </p>
            <p>
              The careers in career box depend on selected species. You can only select careers that are available for
              that species. If the species is selected as random, the only career choice is also random.
            </p>
            <p>
              You can use custom careers to generate characters too. The only limitation is that you have to pre-select
              that career in the career box below. If the career field is set to random, the generator will randomly
              select a career (available for selected Species) from rulebook careers. Custom career will never be
              chosen.
            </p>
            <p>
              Class trappings are added to the character sheet but career specific trappings are not and have to be
              added manually afterward.
            </p>
            <p>Generating will override all current entries on the character sheet.</p>
          </b-collapse>

          <b-row>
            <b-col md="6">
              <b-form-group label="Species">
                <b-form-select :options="genLvl1species" v-model="selectedGenLvl1Species"></b-form-select>
              </b-form-group>
            </b-col>

            <b-col md="6">
              <b-form-group label="Career">
                <b-form-select :options="genLvl1Careers" v-model="selectedGenLvl1Career"></b-form-select>
              </b-form-group>
            </b-col>
          </b-row>
          <b-button @click="genLvl1Details = !genLvl1Details" variant="primary" class="mr-2 mb-1" size="sm">
            {{ genLvl1Details ? "Hide" : "Show" }} Details
          </b-button>
          <b-button
            variant="primary"
            class="mr-2 mb-1"
            size="sm"
            :disabled="!generateEnable || !element.canEdit || !allDataLoaded"
            @click="genCharacter(1, selectedGenLvl1Species, selectedGenLvl1Career)"
          >
            Generate
          </b-button>
        </b-card>

        <b-card title="Generate Advanced Character">
          <p>Fill out character sheet automatically by randomly generating an advanced character (level 2-4).</p>
          <b-collapse id="generation-n-details" class="mt-2" :visible="genLvlnDetails">
            <p>
              High level characters are generated by creating level 1 character and then leveling it up. At each level,
              the character gets 2 talents, 5 attribute advances, and 5 times number of sills for that level (30, 20,
              10) of skill advances. Skill advances are allocated to the skills from the level character is on. Before
              advancing to next level, 8 skills are selected at random from all available skills (all levels) and
              advanced enough to satisfy criteria of career advancement. Attributes are increased so that each one has
              enough of advances to level up the career.
            </p>
            <p>Generating will override all current entries on the character sheet.</p>
          </b-collapse>

          <b-row>
            <b-col md="6">
              <b-form-group label="Species">
                <b-form-select :options="speciesOptions" v-model="selectedGenLvlnSpecies"></b-form-select>
              </b-form-group>
            </b-col>

            <b-col md="6">
              <b-form-group label="Career">
                <b-form-select :options="genLvlnCareers" v-model="selectedGenLvlnCareer"></b-form-select>
              </b-form-group>
            </b-col>

            <b-col md="6">
              <b-form-group label="Level">
                <b-form-select
                  :options="[
                    { value: 2, text: 'Level 2' },
                    { value: 3, text: 'Level 3' },
                    { value: 4, text: 'Level 4' },
                  ]"
                  v-model="generationLevel"
                ></b-form-select>
              </b-form-group>
            </b-col>
          </b-row>
          <b-button @click="genLvlnDetails = !genLvlnDetails" variant="primary" class="mr-2 mb-1" size="sm">
            {{ genLvlnDetails ? "Hide" : "Show" }} Details
          </b-button>
          <b-button
            variant="primary"
            class="mr-2 mb-1"
            size="sm"
            :disabled="!generateEnable || !element.canEdit || !allDataLoaded || selectedGenLvlnCareer === -1"
            @click="genCharacter(generationLevel, selectedGenLvlnSpecies, selectedGenLvlnCareer)"
          >
            Generate
          </b-button>
        </b-card>
      </div>

      <validation-observer ref="observer" v-slot="{ handleSubmit, failed }">
        <b-form id="edit-character" @submit.stop.prevent="handleSubmit(validateAndSubmit)">
          <b-alert variant="success" :fade="true" :show="saveSuccessCountdown" @dismissed="saveSuccessCountdown = 0"
            >Character saved successfully.
          </b-alert>

          <b-row>
            <b-col md="6">
              <ValidationProvider v-slot="{ errors, valid }" :rules="nameValid" name="Name">
                <b-form-group label="Name" label-for="name-input">
                  <b-input-group>
                    <b-form-input id="name-input" :disabled="!element.canEdit" v-model="element.name" type="text">
                    </b-form-input>
                    <b-input-group-append>
                      <b-button variant="primary" @click="genName" :disabled="!element.canEdit">Generate </b-button>
                    </b-input-group-append>
                  </b-input-group>
                  <b-form-invalid-feedback :state="invFeedState(errors, valid)">
                    {{ errors[0] }}
                  </b-form-invalid-feedback>
                </b-form-group>
              </ValidationProvider>

              <b-form-group label="Species" label-for="species-input">
                <b-form-select
                  id="species-input"
                  :disabled="!element.canEdit"
                  :options="speciesOptions"
                  v-model="element.species"
                >
                </b-form-select>
              </b-form-group>

              <b-row>
                <b-col sm="6">
                  <ValidationProvider
                    v-slot="{ errors, valid }"
                    :rules="{
                      required: true,
                      between: { min: 0, max: 1000 },
                      integer: true,
                    }"
                    name="Fate"
                  >
                    <b-form-group label="Fate" label-for="fate-input">
                      <b-form-input
                        id="fate-input"
                        :disabled="!element.canEdit"
                        :number="true"
                        v-model="element.fate"
                        type="number"
                      >
                      </b-form-input>
                      <b-form-invalid-feedback :state="invFeedState(errors, valid)">
                        {{ errors[0] }}
                      </b-form-invalid-feedback>
                    </b-form-group>
                  </ValidationProvider>
                </b-col>
                <b-col sm="6">
                  <ValidationProvider
                    v-slot="{ errors, valid }"
                    :rules="{
                      required: true,
                      between: { min: 0, max: 1000 },
                      integer: true,
                    }"
                    name="Fortune"
                  >
                    <b-form-group label="Fortune" label-for="fortune-input">
                      <b-form-input
                        id="fortune-input"
                        :disabled="!element.canEdit"
                        :number="true"
                        v-model="element.fortune"
                        type="number"
                      >
                      </b-form-input>
                      <b-form-invalid-feedback :state="invFeedState(errors, valid)">
                        {{ errors[0] }}
                      </b-form-invalid-feedback>
                    </b-form-group>
                  </ValidationProvider>
                </b-col>
              </b-row>

              <b-row>
                <b-col sm="6">
                  <ValidationProvider
                    v-slot="{ errors, valid }"
                    :rules="{
                      required: true,
                      between: { min: 0, max: 1000 },
                      integer: true,
                    }"
                    name="Resilience"
                  >
                    <b-form-group label="Resilience" label-for="resilience-input">
                      <b-form-input
                        id="resilience-input"
                        :disabled="!element.canEdit"
                        :number="true"
                        v-model="element.resilience"
                        type="number"
                      >
                      </b-form-input>
                      <b-form-invalid-feedback :state="invFeedState(errors, valid)">
                        {{ errors[0] }}
                      </b-form-invalid-feedback>
                    </b-form-group>
                  </ValidationProvider>
                </b-col>
                <b-col sm="6">
                  <ValidationProvider
                    v-slot="{ errors, valid }"
                    :rules="{
                      required: true,
                      between: { min: 0, max: 1000 },
                      integer: true,
                    }"
                    name="Resolve"
                  >
                    <b-form-group label="Resolve" label-for="resolve-input">
                      <b-form-input
                        id="resolve-input"
                        :disabled="!element.canEdit"
                        :number="true"
                        v-model="element.resolve"
                        type="number"
                      >
                      </b-form-input>
                      <b-form-invalid-feedback :state="invFeedState(errors, valid)">
                        {{ errors[0] }}
                      </b-form-invalid-feedback>
                    </b-form-group>
                  </ValidationProvider>
                </b-col>
              </b-row>

              <b-row>
                <b-col sm="4">
                  <ValidationProvider
                    v-slot="{ errors, valid }"
                    :rules="{
                      required: true,
                      between: { min: 0, max: 10000 },
                      integer: true,
                    }"
                    name="Brass Pennies"
                  >
                    <b-form-group label="Brass Pennies" label-for="brass-input">
                      <b-form-input
                        id="brass-input"
                        :disabled="!element.canEdit"
                        :number="true"
                        v-model="element.brass"
                        type="number"
                      >
                      </b-form-input>
                      <b-form-invalid-feedback :state="invFeedState(errors, valid)">
                        {{ errors[0] }}
                      </b-form-invalid-feedback>
                    </b-form-group>
                  </ValidationProvider>
                </b-col>
                <b-col sm="4">
                  <ValidationProvider
                    v-slot="{ errors, valid }"
                    :rules="{
                      required: true,
                      between: { min: 0, max: 10000 },
                      integer: true,
                    }"
                    name="Silver Shillings"
                  >
                    <b-form-group label="Silver Shillings" label-for="silver-input">
                      <b-form-input
                        id="silver-input"
                        :disabled="!element.canEdit"
                        :number="true"
                        v-model="element.silver"
                        type="number"
                      >
                      </b-form-input>
                      <b-form-invalid-feedback :state="invFeedState(errors, valid)">
                        {{ errors[0] }}
                      </b-form-invalid-feedback>
                    </b-form-group>
                  </ValidationProvider>
                </b-col>
                <b-col sm="4">
                  <ValidationProvider
                    v-slot="{ errors, valid }"
                    :rules="{
                      required: true,
                      between: { min: 0, max: 1000 },
                      integer: true,
                    }"
                    name="Gold Crowns"
                  >
                    <b-form-group label="Gold Crowns" label-for="gold-input">
                      <b-form-input
                        id="gold-input"
                        :disabled="!element.canEdit"
                        :number="true"
                        v-model="element.gold"
                        type="number"
                      >
                      </b-form-input>
                      <b-form-invalid-feedback :state="invFeedState(errors, valid)">
                        {{ errors[0] }}
                      </b-form-invalid-feedback>
                    </b-form-group>
                  </ValidationProvider>
                </b-col>
              </b-row>

              <b-row>
                <b-col sm="6">
                  <ValidationProvider
                    v-slot="{ errors, valid }"
                    :rules="{
                      required: true,
                      between: { min: 0, max: 10000000 },
                      integer: true,
                    }"
                    name="Spent Experience"
                  >
                    <b-form-group label="Spent Experience" label-for="spent-exp-input">
                      <b-form-input
                        id="spent-exp-input"
                        :disabled="!element.canEdit"
                        :number="true"
                        v-model="element.spentExp"
                        type="number"
                      >
                      </b-form-input>
                      <b-form-invalid-feedback :state="invFeedState(errors, valid)">
                        {{ errors[0] }}
                      </b-form-invalid-feedback>
                    </b-form-group>
                  </ValidationProvider>
                </b-col>
                <b-col sm="6">
                  <ValidationProvider
                    v-slot="{ errors, valid }"
                    :rules="{
                      required: true,
                      between: { min: 0, max: 10000000 },
                      integer: true,
                    }"
                    name="Unspent Experience"
                  >
                    <b-form-group label="Unspent Experience" label-for="unspent-exp-input">
                      <b-form-input
                        id="unspent-exp-input"
                        :disabled="!element.canEdit"
                        :number="true"
                        v-model="element.currentExp"
                        type="number"
                      >
                      </b-form-input>
                      <b-form-invalid-feedback :state="invFeedState(errors, valid)">
                        {{ errors[0] }}
                      </b-form-invalid-feedback>
                    </b-form-group>
                  </ValidationProvider>
                </b-col>
              </b-row>

              <b-row>
                <b-col sm="6">
                  <b-form-group label="Status" label-for="status-input">
                    <b-form-select
                      id="status-input"
                      :disabled="!element.canEdit"
                      :options="statusOptions"
                      v-model="element.status"
                    >
                    </b-form-select>
                  </b-form-group>
                </b-col>
                <b-col sm="6">
                  <b-form-group label="Standing" label-for="standing-input">
                    <b-form-select
                      id="standing-input"
                      :disabled="!element.canEdit"
                      :options="standingOptions"
                      v-model="element.standing"
                    >
                    </b-form-select>
                  </b-form-group>
                </b-col>
              </b-row>

              <b-row>
                <b-col sm="6">
                  <ValidationProvider
                    v-slot="{ errors, valid }"
                    :rules="{
                      required: true,
                      between: { min: 0, max: 1000 },
                      integer: true,
                    }"
                    name="Sin Points"
                  >
                    <b-form-group label="Sin Points" label-for="sin-input">
                      <b-form-input
                        id="sin-input"
                        :disabled="!element.canEdit"
                        :number="true"
                        v-model="element.sin"
                        type="number"
                      >
                      </b-form-input>
                      <b-form-invalid-feedback :state="invFeedState(errors, valid)">
                        {{ errors[0] }}
                      </b-form-invalid-feedback>
                    </b-form-group>
                  </ValidationProvider>
                </b-col>
                <b-col sm="6">
                  <ValidationProvider
                    v-slot="{ errors, valid }"
                    :rules="{
                      required: true,
                      between: { min: 0, max: 1000 },
                      integer: true,
                    }"
                    name="Corruption Points"
                  >
                    <b-form-group label="Corruption Points" label-for="corruption-input">
                      <b-form-input
                        id="corruption-input"
                        :disabled="!element.canEdit"
                        :number="true"
                        v-model="element.corruption"
                        type="number"
                      >
                      </b-form-input>
                      <b-form-invalid-feedback :state="invFeedState(errors, valid)">
                        {{ errors[0] }}
                      </b-form-invalid-feedback>
                    </b-form-group>
                  </ValidationProvider>
                </b-col>
              </b-row>

              <b-row>
                <b-col sm="6">
                  <b-form-group>
                    <div>Movement</div>
                    <div class="mt-2">{{ movement }}</div>
                  </b-form-group>
                </b-col>
                <b-col sm="6">
                  <b-form-group>
                    <div>Wounds</div>
                    <div class="mt-2">{{ wounds }}</div>
                  </b-form-group>
                </b-col>
              </b-row>
            </b-col>

            <b-col md="6">
              <b-form-group label="Career">
                <div class="border">
                  <CharacterCareerTable
                    :disabled="!element.canEdit"
                    :pastCareers="initialPastCareers"
                    :currentCareer.sync="element.career"
                    @pastCareerChanged="updatePastCareer"
                    class="ml-2 mr-2"
                    @stateChanged="validCareer = $event"
                    @listOfCareers="listOfCareers = $event"
                  ></CharacterCareerTable>
                </div>
                <b-form-invalid-feedback :state="validCareer"> Current Career is required </b-form-invalid-feedback>
              </b-form-group>
              <ValidationProvider v-slot="{ errors, valid }" :rules="descValid" name="Description">
                <b-form-group label="Description" label-for="description-input">
                  <b-form-textarea
                    id="description-input"
                    :disabled="!element.canEdit"
                    v-model="element.description"
                    rows="3"
                    max-rows="50"
                  >
                  </b-form-textarea>
                  <b-button variant="primary" @click="genDesc" :disabled="!element.canEdit" size="sm" class="mt-2"
                    >Generate
                  </b-button>
                  <b-form-invalid-feedback :state="invFeedState(errors, valid)">
                    {{ errors[0] }}
                  </b-form-invalid-feedback>
                </b-form-group>
              </ValidationProvider>

              <ValidationProvider v-slot="{ errors, valid }" :rules="descValid" name="Notes">
                <b-form-group label="Notes" label-for="notes-input">
                  <b-form-textarea
                    id="notes-input"
                    :disabled="!element.canEdit"
                    v-model="element.notes"
                    rows="3"
                    max-rows="50"
                  >
                  </b-form-textarea>
                  <b-form-invalid-feedback :state="invFeedState(errors, valid)">
                    {{ errors[0] }}
                  </b-form-invalid-feedback>
                </b-form-group>
              </ValidationProvider>
            </b-col>
          </b-row>

          <b-row>
            <b-col>
              <b-form-group label="Attributes">
                <b-row>
                  <b-col xl="4">
                    <b-table-simple :responsive="true">
                      <b-thead>
                        <b-th></b-th>
                        <b-th>WS</b-th>
                        <b-th>BS</b-th>
                      </b-thead>
                      <b-tbody>
                        <b-tr>
                          <b-th>Rolls</b-th>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeRolls.WS"
                            >
                            </b-form-input>
                          </b-td>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeRolls.BS"
                            >
                            </b-form-input>
                          </b-td>
                        </b-tr>
                        <b-tr>
                          <b-th>Racial</b-th>
                          <b-td>{{ racial.WS }}</b-td>
                          <b-td>{{ racial.BS }}</b-td>
                        </b-tr>
                        <b-tr>
                          <b-th>Base</b-th>
                          <b-td>{{ base.WS }}</b-td>
                          <b-td>{{ base.BS }}</b-td>
                        </b-tr>
                        <b-tr>
                          <b-th>Adv</b-th>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeAdvances.WS"
                            >
                            </b-form-input>
                          </b-td>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeAdvances.BS"
                            >
                            </b-form-input>
                          </b-td>
                        </b-tr>
                        <b-tr>
                          <b-th>Total</b-th>
                          <b-td>{{ total.WS }}</b-td>
                          <b-td>{{ total.BS }}</b-td>
                        </b-tr>
                      </b-tbody>
                    </b-table-simple>
                  </b-col>
                  <b-col xl="4">
                    <b-table-simple :responsive="true">
                      <b-thead>
                        <b-th>S</b-th>
                        <b-th>T</b-th>
                        <b-th>I</b-th>
                        <b-th>Ag</b-th>
                      </b-thead>
                      <b-tbody>
                        <b-tr>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeRolls.S"
                            >
                            </b-form-input>
                          </b-td>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeRolls.T"
                            >
                            </b-form-input>
                          </b-td>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeRolls.I"
                            >
                            </b-form-input>
                          </b-td>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeRolls.Ag"
                            >
                            </b-form-input>
                          </b-td>
                        </b-tr>
                        <b-tr>
                          <b-td>{{ racial.S }}</b-td>
                          <b-td>{{ racial.T }}</b-td>
                          <b-td>{{ racial.I }}</b-td>
                          <b-td>{{ racial.Ag }}</b-td>
                        </b-tr>
                        <b-tr>
                          <b-td>{{ base.S }}</b-td>
                          <b-td>{{ base.T }}</b-td>
                          <b-td>{{ base.I }}</b-td>
                          <b-td>{{ base.Ag }}</b-td>
                        </b-tr>
                        <b-tr>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeAdvances.S"
                            >
                            </b-form-input>
                          </b-td>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeAdvances.T"
                            >
                            </b-form-input>
                          </b-td>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeAdvances.I"
                            >
                            </b-form-input>
                          </b-td>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeAdvances.Ag"
                            >
                            </b-form-input>
                          </b-td>
                        </b-tr>
                        <b-tr>
                          <b-td>{{ total.S }}</b-td>
                          <b-td>{{ total.T }}</b-td>
                          <b-td>{{ total.I }}</b-td>
                          <b-td>{{ total.Ag }}</b-td>
                        </b-tr>
                      </b-tbody>
                    </b-table-simple>
                  </b-col>
                  <b-col xl="4">
                    <b-table-simple :responsive="true">
                      <b-thead>
                        <b-th>Dex</b-th>
                        <b-th>Int</b-th>
                        <b-th>WP</b-th>
                        <b-th>Fel</b-th>
                      </b-thead>
                      <b-tbody>
                        <b-tr>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeRolls.Dex"
                            >
                            </b-form-input>
                          </b-td>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeRolls.Int"
                            >
                            </b-form-input>
                          </b-td>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeRolls.WP"
                            >
                            </b-form-input>
                          </b-td>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeRolls.Fel"
                            >
                            </b-form-input>
                          </b-td>
                        </b-tr>
                        <b-tr>
                          <b-td>{{ racial.Dex }}</b-td>
                          <b-td>{{ racial.Int }}</b-td>
                          <b-td>{{ racial.WP }}</b-td>
                          <b-td>{{ racial.Fel }}</b-td>
                        </b-tr>
                        <b-tr>
                          <b-td>{{ base.Dex }}</b-td>
                          <b-td>{{ base.Int }}</b-td>
                          <b-td>{{ base.WP }}</b-td>
                          <b-td>{{ base.Fel }}</b-td>
                        </b-tr>
                        <b-tr>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeAdvances.Dex"
                            >
                            </b-form-input>
                          </b-td>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeAdvances.Int"
                            >
                            </b-form-input>
                          </b-td>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeAdvances.WP"
                            >
                            </b-form-input>
                          </b-td>
                          <b-td>
                            <b-form-input
                              :disabled="!element.canEdit"
                              :number="true"
                              min="0"
                              max="99"
                              type="number"
                              v-model="element.attributeAdvances.Fel"
                            >
                            </b-form-input>
                          </b-td>
                        </b-tr>
                        <b-tr>
                          <b-td>{{ total.Dex }}</b-td>
                          <b-td>{{ total.Int }}</b-td>
                          <b-td>{{ total.WP }}</b-td>
                          <b-td>{{ total.Fel }}</b-td>
                        </b-tr>
                      </b-tbody>
                    </b-table-simple>
                  </b-col>
                </b-row>
                <b-button variant="primary" size="sm" @click="genRolls" :disabled="!element.canEdit">
                  Generate Rolls
                </b-button>
                <b-form-invalid-feedback :state="validBase">
                  Invalid value of one or more Base Attributes. Base Attributes have to be integers between 0 and 99.
                </b-form-invalid-feedback>
                <b-form-invalid-feedback :state="validAdv">
                  Invalid value of one or more Attribute Advances. Attribute Advances have to be integers between 0 and
                  99.
                </b-form-invalid-feedback>
              </b-form-group>
            </b-col>
          </b-row>

          <b-row>
            <b-col md="6">
              <b-form-group label="Skills">
                <CharacterSkillsTable
                  :disabled="!element.canEdit"
                  :characterSkills="initialSkills"
                  :characterAtts="total"
                  :canSave="validCustom && !failed"
                  @listOfSkills="listOfSkills = $event"
                  @selectedChanged="updateIdNumberList(element.skills, $event)"
                  @stateChanged="validSkills = $event"
                  @createNew="validateAndSubmit('skill')"
                ></CharacterSkillsTable>
                <b-form-invalid-feedback :state="validSkills">
                  Invalid value of one or more Skills. Skills have to be integer numbers between 0 and 1000.
                </b-form-invalid-feedback>
              </b-form-group>
            </b-col>
            <b-col md="6">
              <b-form-group label="Talents">
                <CharacterTalentsTable
                  :disabled="!element.canEdit"
                  :characterTalents="initialTalents"
                  :characterAtts="total"
                  :canSave="validCustom && !failed"
                  @listOfTalents="listOfTalents = $event"
                  @selectedChanged="updateIdNumberList(element.talents, $event)"
                  @stateChanged="validTalents = $event"
                  @createNew="validateAndSubmit('talent')"
                ></CharacterTalentsTable>
                <b-form-invalid-feedback :state="validTalents">
                  Invalid value of one or more Talents.
                </b-form-invalid-feedback>
              </b-form-group>
            </b-col>
          </b-row>

          <b-row>
            <b-col md="12">
              <b-form-group label="Trappings">
                <CharacterItemsTable
                  :disabled="!element.canEdit"
                  :canSave="validCustom && !failed"
                  :itemsEquipped="initialEquippedItems"
                  :itemsCarried="initialCarriedItems"
                  :itemsStored="initialStoredItems"
                  :classItems="classItems"
                  @equippedChanged="updateIdNumberList(element.equippedItems, $event)"
                  @carriedChanged="updateIdNumberList(element.carriedItems, $event)"
                  @storedChanged="updateIdNumberList(element.storedItems, $event)"
                  @stateChanged="validItems = $event"
                  @createNew="validateAndSubmit('item')"
                ></CharacterItemsTable>
                <b-form-invalid-feedback :state="validItems">
                  Invalid number of one or more Items. Item quantity number has to be an integer between 0 and 1000.
                </b-form-invalid-feedback>
              </b-form-group>
            </b-col>
          </b-row>

          <b-row>
            <b-col md="6">
              <b-form-group label="Spells/Prayers">
                <CharacterSpellsTable
                  :disabled="!element.canEdit"
                  :canSave="validCustom && !failed"
                  :selectedItems="initialSpells"
                  @changed="updateIdList(element.spells, $event)"
                  @createNew="validateAndSubmit('spell')"
                ></CharacterSpellsTable>
              </b-form-group>
            </b-col>

            <b-col md="6">
              <b-form-group label="Mutations">
                <CharacterMutationsTable
                  :disabled="!element.canEdit"
                  :canSave="validCustom && !failed"
                  :selectedItems="initialMutations"
                  @changed="updateIdList(element.mutations, $event)"
                  @createNew="validateAndSubmit('mutation')"
                ></CharacterMutationsTable>
              </b-form-group>
            </b-col>
          </b-row>

          <b-row>
            <b-col>
              <PublicElementBox v-if="element.canEdit" v-model="element.shared" elementName="Character" />

              <CreateSubmit
                :showAddAnother="showAddAnother"
                :disabled="!element.canEdit"
                :submitting="submitting"
                @goBack="goBack"
                v-model="addAnother"
              ></CreateSubmit>
            </b-col>
          </b-row>
        </b-form>
      </validation-observer>
    </b-container>
  </div>
</template>

<script>
import CreateElement from "../CreateElement.vue";
import CreateSubmit from "../CreateSubmit.vue";
import CharacterCareerTable from "./CharacterCareerTable.vue";
import CharacterSkillsTable from "./CharacterSkillsTable.vue";
import CharacterTalentsTable from "./CharacterTalentsTable.vue";
import CharacterItemsTable from "./CharacterItemsTable.vue";
import CharacterSpellsTable from "./CharacterSpellsTable.vue";
import CharacterMutationsTable from "./CharacterMutationsTable.vue";
import PublicElementBox from "../PublicElementBox.vue";
import { ValidationObserver, ValidationProvider } from "vee-validate";
import generateName from "../../../services/wh/characterGeneration/nameGeneration";
import generateDescription from "../../../services/wh/characterGeneration/descriptionGeneration";
import generateCharacter from "../../../services/wh/characterGeneration/characterGeneration";
import { generateRolls } from "../../../services/wh/characterGeneration/attGeneration";
import { authRequest } from "../../../services/auth";
import { logoutIfUnauthorized } from "../../../utils/navigation";
import {
  generateEmptyCharacter,
  CharacterApi,
  species,
  getWounds,
  getMovement,
  getRacialAttributes,
  getTotalAttributes,
  getBaseAttributes,
  compareCharacter,
  generateNewCharacter,
} from "../../../services/wh/character";
import { statusStandings, statusTiers } from "../../../services/wh/career";

export default {
  name: "CreateCharacter",
  mixins: [CreateElement],
  components: {
    ValidationObserver,
    ValidationProvider,
    CreateSubmit,
    CharacterCareerTable,
    CharacterSkillsTable,
    CharacterTalentsTable,
    CharacterItemsTable,
    CharacterSpellsTable,
    CharacterMutationsTable,
    PublicElementBox,
  },
  data() {
    return {
      elementApi: new CharacterApi(authRequest),

      element: generateEmptyCharacter(),
      elementOriginal: generateEmptyCharacter(),

      speciesOptions: Object.keys(species).map((key) => {
        return { value: parseInt(key), text: species[key] };
      }),
      statusOptions: Object.keys(statusTiers).map((key) => {
        return { value: parseInt(key), text: statusTiers[key] };
      }),

      standingOptions: Object.keys(statusStandings).map((key) => {
        return { value: parseInt(key), text: statusStandings[key] };
      }),

      validSkills: true,
      validTalents: true,
      validCareer: true,
      validItems: true,

      initialPastCareers: [],
      initialSkills: [],
      initialTalents: [],
      initialEquippedItems: [],
      initialCarriedItems: [],
      initialStoredItems: [],
      initialSpells: [],
      initialMutations: [],

      selectedGenLvl1Species: -1,
      selectedGenLvlnSpecies: 0,
      selectedGenLvl1Career: -1,
      selectedGenLvlnCareer: -1,
      genLvl1Details: false,
      genLvlnDetails: false,
      listOfCareers: [],
      listOfSkills: [],
      listOfTalents: [],
      createEnabled: true,
      generationProps: null,
      generationLevel: 2,
    };
  },
  created() {
    this.elementType = "character";
    this.initializeElement();
    this.loadGenerationProps();
  },
  computed: {
    allDataLoaded() {
      return (
        !!this.generationProps &&
        !!this.listOfTalents.length &&
        !!this.listOfSkills.length &&
        !!this.listOfCareers.length
      );
    },
    classItems() {
      if (this.listOfCareers.length < 1 || !Object.hasOwn(this.element.career, "id")) {
        return {};
      } else {
        let selectedCareer = this.listOfCareers.find((x) => x.id === this.element.career.id);

        if (selectedCareer && this.generationProps && Object.hasOwn(this.generationProps, "class_items")) {
          return this.generationProps.class_items[selectedCareer.class];
        } else {
          return {};
        }
      }
    },
    genLvl1species(includeRandom) {
      let species = JSON.parse(JSON.stringify(this.speciesOptions));
      if (includeRandom) {
        species.unshift({ value: -1, text: "Random (+20 XP)" });
      }
      return species;
    },
    genLvl1Careers() {
      return this.generateCareers(true, this.selectedGenLvl1Species);
    },
    genLvlnCareers() {
      return this.generateCareers(false, this.selectedGenLvlnSpecies);
    },
    generateEnable() {
      return this.listOfCareers.length > 0;
    },
    wounds() {
      return getWounds(this.element);
    },
    movement() {
      return getMovement(this.element);
    },
    racial() {
      return getRacialAttributes(this.element);
    },
    total() {
      return getTotalAttributes(this.element);
    },
    base() {
      return getBaseAttributes(this.element);
    },
    validBase() {
      for (let value of Object.values(this.base)) {
        if (value > 99 || value < 0 || !Number.isInteger(value)) {
          return false;
        }
      }
      return true;
    },
    validAdv() {
      for (let value of Object.values(this.element.attributeAdvances)) {
        if (value > 99 || value < 0 || !Number.isInteger(value)) {
          return false;
        }
      }
      return true;
    },
    validCustom() {
      return (
        this.validBase && this.validAdv && this.validSkills && this.validCareer && this.validItems && this.validTalents
      );
    },
  },
  methods: {
    generateCareers(includeRandom, species) {
      let careers = this.listOfCareers
        .map((x, idx) => {
          let disabled = !x.species.includes(species);
          return { value: idx, text: x.name, disabled: disabled };
        })
        .filter((x) => x.disabled === false);

      careers.sort(function (x, y) {
        if (x.text === y.text) {
          return 0;
        } else {
          return x.text < y.text ? -1 : 1;
        }
      });

      if (includeRandom) {
        careers.unshift({
          value: -1,
          text: "Random (+50 XP)",
          disabled: false,
        });
      } else {
        careers.unshift({ value: -1, text: "Select Career", disabled: false });
      }

      return careers;
    },
    async loadGenerationProps() {
      let serverResp = null;
      try {
        serverResp = await logoutIfUnauthorized(authRequest.get)("/api/generation_props");
        this.generationProps = serverResp.data.data;
      } catch (error) {
        this.addError();
      }
    },
    genCharacter(level, species, career) {
      let char = generateCharacter(
        species,
        career,
        this.listOfCareers,
        this.listOfSkills,
        this.listOfTalents,
        this.generationProps,
        level
      );
      Object.assign(this.element, char);
      this.resetTables();
    },
    genName() {
      this.element.name = generateName(this.element.species, 2);
    },
    genDesc() {
      this.element.description = generateDescription(this.element.species);
    },
    updateIdNumberList(idNumberList, newValue) {
      let item = idNumberList.find((x) => x.id === newValue.id);
      if (item) {
        if (newValue.number !== 0) {
          item.number = newValue.number;
        } else {
          idNumberList.splice(idNumberList.indexOf(item), 1);
        }
      } else {
        if (newValue !== 0) {
          idNumberList.push(newValue);
        }
      }
    },
    updateIdList(idList, newValue) {
      let item = idList.find((x) => x === newValue.id);
      if (item) {
        if (!newValue.selected) {
          idList.splice(idList.indexOf(item), 1);
        }
      } else {
        if (newValue.selected) {
          idList.push(newValue.id);
        }
      }
    },
    updatePastCareer(newValue) {
      let item = this.element.careerPath.find((x) => x.id === newValue.id && x.number === newValue.number);
      if (item) {
        if (!newValue.selected) {
          this.element.careerPath.splice(this.element.careerPath.indexOf(item), 1);
        }
      } else {
        if (newValue.selected) {
          this.element.careerPath.push({
            id: newValue.id,
            number: newValue.number,
          });
        }
      }
    },
    genRolls() {
      this.element.attributeRolls = generateRolls();
    },
    validateAndSubmit(redirectElementType = null) {
      if (this.validCustom) {
        return this.submitForm(redirectElementType);
      }
    },
    formModified() {
      return !compareCharacter(this.element, this.elementOriginal);
    },
    setElementToNew(canEdit) {
      this.element = generateNewCharacter(canEdit);
      this.elementOriginal = generateNewCharacter(canEdit);
    },
    resetTables() {
      this.initialPastCareers = JSON.parse(JSON.stringify(this.element.careerPath));
      this.initialSkills = JSON.parse(JSON.stringify(this.element.skills));
      this.initialTalents = JSON.parse(JSON.stringify(this.element.talents));
      this.initialEquippedItems = JSON.parse(JSON.stringify(this.element.equippedItems));
      this.initialCarriedItems = JSON.parse(JSON.stringify(this.element.carriedItems));
      this.initialStoredItems = JSON.parse(JSON.stringify(this.element.storedItems));
      this.initialSpells = JSON.parse(JSON.stringify(this.element.spells));
      this.initialMutations = JSON.parse(JSON.stringify(this.element.mutations));
    },
  },
  watch: {
    selectedGenLvl1Species(newVal) {
      if (
        newVal !== -1 &&
        this.selectedGenLvl1Career !== -1 &&
        !this.listOfCareers[this.selectedGenLvl1Career].species.includes(newVal)
      ) {
        this.selectedGenLvl1Career = -1;
      } else if (newVal === -1) {
        this.selectedGenLvl1Career = -1;
      }
    },
    selectedGenLvlnSpecies(newVal) {
      if (this.selectedGenLvlnCareer > -1 && !this.listOfCareers[this.selectedGenLvlnCareer].species.includes(newVal)) {
        this.selectedGenLvlnCareer = -1;
      }
    },
    "element.career"(newVal, oldVal) {
      if (!Object.hasOwn(oldVal, "id")) {
        this.elementOriginal.career = { id: newVal.id, number: newVal.number };
      }
    },
  },
};
</script>

<style scoped></style>
