<template>
  <div class="character">
    <b-container>
      <h1>{{ titlePrefix }} Character</h1>

      <div v-if="errors.length" class="text-danger field-validation-error mt-3">
        <ul>
          <li v-for="error in errors" v-bind:key="error">{{ error }}</li>
        </ul>
      </div>

      <div v-if="id === 'create' && createEnabled" class="mb-2 mt-2">
        <p>
          Create a new character. You can either fill out the character sheet manually use on of the random generators.
        </p>

        <div>
          <b-button class="mr-2 mb-2" variant="primary" size="sm" @click="genLvl = !genLvl"> Generate Random</b-button>
        </div>
        <b-collapse id="generation-1" class="mt-2" :visible="genLvl">
          <b-card title="Generate Advanced Character">
            <p>Fill out character sheet automatically by randomly generating character (level 1-4).</p>
            <b-collapse id="generation-n-details" class="mt-2" :visible="genDetails">
              <p>
                The generation process of a level 1 character follows all steps from character chapter of the rulebook
                with the exception that species and career cannot be chosen as random at this moment.
              </p>
              <p>
                The careers in career box depend on selected species. You can only select careers that are available for
                that species. You can use custom careers to generate characters too.
              </p>
              <p>
                Class trappings are added to the character sheet but career specific trappings are not and have to be
                added manually afterward.
              </p>
              <p>Generating will override all current entries on the character sheet.</p>
              <p>
                High level characters are generated by creating level 1 character and then leveling it up. At each
                level, the character gets 2 talents, 5 attribute advances, and 5 times number of sills for that level
                (30, 20, 10) of skill advances. Skill advances are allocated to the skills from the level character is
                on. Before advancing to next level, 8 skills are selected at random from all available skills (all
                levels) and advanced enough to satisfy criteria of career advancement. Attributes are increased so that
                each one has enough of advances to level up the career.
              </p>
              <p>Generating will override all current entries on the character sheet.</p>
            </b-collapse>

            <b-row>
              <b-col md="6">
                <b-form-group label="Species">
                  <b-form-select
                    :options="speciesWithRegionsOptions"
                    v-model="selectedGenSpeciesWithRegion"
                  ></b-form-select>
                </b-form-group>
              </b-col>

              <b-col md="6">
                <b-form-group label="Career">
                  <b-form-select :options="genCareers" v-model="selectedGenCareer"></b-form-select>
                </b-form-group>
              </b-col>

              <b-col md="6">
                <b-form-group label="Level">
                  <b-form-select
                    :options="[
                      { value: 1, text: 'Level 1' },
                      { value: 2, text: 'Level 2' },
                      { value: 3, text: 'Level 3' },
                      { value: 4, text: 'Level 4' },
                    ]"
                    v-model="generationLevel"
                  ></b-form-select>
                </b-form-group>
              </b-col>
            </b-row>
            <b-button class="mr-2 mb-1" variant="primary" size="sm" @click="genLvl = false"> Hide</b-button>
            <b-button @click="genDetails = !genDetails" variant="primary" class="mr-2 mb-1" size="sm">
              {{ genDetails ? "Hide" : "Show" }} Details
            </b-button>
            <b-button
              variant="primary"
              class="mr-2 mb-1"
              size="sm"
              :disabled="!generateEnable || !element.canEdit || !allDataLoaded || selectedGenCareer === -1"
              @click="genCharacter(generationLevel, selectedGenSpeciesWithRegion, selectedGenCareer)"
            >
              Generate
            </b-button>
          </b-card>
        </b-collapse>
      </div>

      <b-form id="edit-character" @submit.stop.prevent="submit">
        <b-alert variant="success" :fade="true" :show="saveSuccessCountdown" @dismissed="saveSuccessCountdown = 0"
          >Character saved successfully.
        </b-alert>

        <b-row>
          <b-col md="6">
            <b-form-group label="Name" label-for="name-input">
              <b-input-group>
                <b-form-input id="name-input" :disabled="!element.canEdit" v-model="element.name" type="text">
                </b-form-input>
                <b-input-group-append>
                  <b-button variant="primary" @click="genName" :disabled="!element.canEdit">Generate</b-button>
                </b-input-group-append>
              </b-input-group>
              <b-form-invalid-feedback :state="validName[0]">{{ validName[1] }}</b-form-invalid-feedback>
            </b-form-group>

            <b-form-group label="Species" label-for="species-input">
              <b-form-select
                id="species-input"
                :disabled="!element.canEdit"
                :options="speciesWithRegionsOptions"
                v-model="element.speciesWithRegion"
              >
              </b-form-select>
            </b-form-group>

            <b-row>
              <b-col sm="6">
                <b-form-group label="Fate" label-for="fate-input">
                  <b-form-input
                    id="fate-input"
                    :disabled="!element.canEdit"
                    :number="true"
                    v-model="element.fate"
                    type="number"
                  >
                  </b-form-input>
                  <b-form-invalid-feedback :state="validFate[0]">{{ validFate[1] }}</b-form-invalid-feedback>
                </b-form-group>
              </b-col>
              <b-col sm="6">
                <b-form-group label="Fortune" label-for="fortune-input">
                  <b-form-input
                    id="fortune-input"
                    :disabled="!element.canEdit"
                    :number="true"
                    v-model="element.fortune"
                    type="number"
                  >
                  </b-form-input>
                  <b-form-invalid-feedback :state="validFortune[0]">{{ validFortune[1] }}</b-form-invalid-feedback>
                </b-form-group>
              </b-col>
            </b-row>

            <b-row>
              <b-col sm="6">
                <b-form-group label="Resilience" label-for="resilience-input">
                  <b-form-input
                    id="resilience-input"
                    :disabled="!element.canEdit"
                    :number="true"
                    v-model="element.resilience"
                    type="number"
                  >
                  </b-form-input>
                  <b-form-invalid-feedback :state="validResilience[0]"
                    >{{ validResilience[1] }}
                  </b-form-invalid-feedback>
                </b-form-group>
              </b-col>
              <b-col sm="6">
                <b-form-group label="Resolve" label-for="resolve-input">
                  <b-form-input
                    id="resolve-input"
                    :disabled="!element.canEdit"
                    :number="true"
                    v-model="element.resolve"
                    type="number"
                  >
                  </b-form-input>
                  <b-form-invalid-feedback :state="validResolve[0]">{{ validResolve[1] }}</b-form-invalid-feedback>
                </b-form-group>
              </b-col>
            </b-row>

            <b-row>
              <b-col sm="6">
                <b-button
                  size="sm"
                  variant="primary"
                  class="mb-2"
                  @click="setFateResilience"
                  :disabled="!element.canEdit"
                >
                  Set Fate/Resilience
                </b-button>
              </b-col>
            </b-row>

            <b-row>
              <b-col sm="6">
                <b-form-group label="Status" label-for="status-input">
                  <b-form-select
                    id="status-input"
                    :disabled="!element.canEdit"
                    :options="statusOptions"
                    v-model="element.status"
                  >
                  </b-form-select>
                </b-form-group>
              </b-col>
              <b-col sm="6">
                <b-form-group label="Standing" label-for="standing-input">
                  <b-form-select
                    id="standing-input"
                    :disabled="!element.canEdit"
                    :options="standingOptions"
                    v-model="element.standing"
                  >
                  </b-form-select>
                </b-form-group>
              </b-col>
            </b-row>
            <b-row>
              <b-col sm="6">
                <b-button size="sm" variant="primary" class="mb-2" @click="setStatus" :disabled="!element.canEdit">
                  Set Career Status
                </b-button>
              </b-col>
            </b-row>

            <b-row>
              <b-col sm="4">
                <b-form-group label="Brass Pennies" label-for="brass-input">
                  <b-form-input
                    id="brass-input"
                    :disabled="!element.canEdit"
                    :number="true"
                    v-model="element.brass"
                    type="number"
                  >
                  </b-form-input>
                  <b-form-invalid-feedback :state="validBrass[0]">{{ validBrass[1] }}</b-form-invalid-feedback>
                </b-form-group>
              </b-col>
              <b-col sm="4">
                <b-form-group label="Silver Shillings" label-for="silver-input">
                  <b-form-input
                    id="silver-input"
                    :disabled="!element.canEdit"
                    :number="true"
                    v-model="element.silver"
                    type="number"
                  >
                  </b-form-input>
                  <b-form-invalid-feedback :state="validSilver[0]">{{ validSilver[1] }}</b-form-invalid-feedback>
                </b-form-group>
              </b-col>
              <b-col sm="4">
                <b-form-group label="Gold Crowns" label-for="gold-input">
                  <b-form-input
                    id="gold-input"
                    :disabled="!element.canEdit"
                    :number="true"
                    v-model="element.gold"
                    type="number"
                  >
                  </b-form-input>
                  <b-form-invalid-feedback :state="validGold[0]">{{ validGold[1] }}</b-form-invalid-feedback>
                </b-form-group>
              </b-col>
            </b-row>

            <b-row>
              <b-col sm="6">
                <b-form-group label="Spent Experience" label-for="spent-exp-input">
                  <b-form-input
                    id="spent-exp-input"
                    :disabled="!element.canEdit"
                    :number="true"
                    v-model="element.spentExp"
                    type="number"
                  >
                  </b-form-input>
                  <b-form-invalid-feedback :state="validSpentExp[0]">{{ validSpentExp[1] }}</b-form-invalid-feedback>
                </b-form-group>
              </b-col>
              <b-col sm="6">
                <b-form-group label="Unspent Experience" label-for="unspent-exp-input">
                  <b-form-input
                    id="unspent-exp-input"
                    :disabled="!element.canEdit"
                    :number="true"
                    v-model="element.currentExp"
                    type="number"
                  >
                  </b-form-input>
                  <b-form-invalid-feedback :state="validCurrentExp[0]"
                    >{{ validCurrentExp[1] }}
                  </b-form-invalid-feedback>
                </b-form-group>
              </b-col>
            </b-row>

            <b-row>
              <b-col sm="6">
                <b-form-group label="Sin Points" label-for="sin-input">
                  <b-form-input
                    id="sin-input"
                    :disabled="!element.canEdit"
                    :number="true"
                    v-model="element.sin"
                    type="number"
                  >
                  </b-form-input>
                  <b-form-invalid-feedback :state="validSin[0]">{{ validSin[1] }}</b-form-invalid-feedback>
                </b-form-group>
              </b-col>
              <b-col sm="6">
                <b-form-group label="Corruption Points" label-for="corruption-input">
                  <b-form-input
                    id="corruption-input"
                    :disabled="!element.canEdit"
                    :number="true"
                    v-model="element.corruption"
                    type="number"
                  >
                  </b-form-input>
                  <b-form-invalid-feedback :state="validCorruption[0]"
                    >{{ validCorruption[1] }}
                  </b-form-invalid-feedback>
                </b-form-group>
              </b-col>
            </b-row>

            <b-row>
              <b-col sm="6">
                <b-form-group>
                  <div>Movement</div>
                  <div class="mt-2">{{ movement }}</div>
                </b-form-group>
              </b-col>
              <b-col sm="6">
                <b-form-group>
                  <div>Wounds (unmodified by Hardy)</div>
                  <div class="mt-2">{{ wounds }}</div>
                </b-form-group>
              </b-col>
            </b-row>
          </b-col>

          <b-col md="6">
            <b-form-group label="Career">
              <div class="border">
                <CharacterCareerTable
                  :disabled="!element.canEdit"
                  :pastCareers="initialPastCareers"
                  :currentCareer.sync="element.career"
                  @pastCareerChanged="updatePastCareer"
                  class="ml-2 mr-2"
                  @stateChanged="validCareer = $event"
                  @listOfCareers="listOfCareers = $event"
                ></CharacterCareerTable>
              </div>
              <b-form-invalid-feedback :state="validCareer"> Current Career is required</b-form-invalid-feedback>
            </b-form-group>
            <b-form-group label="Description" label-for="description-input">
              <b-form-textarea
                id="description-input"
                :disabled="!element.canEdit"
                v-model="element.description"
                rows="3"
                max-rows="50"
              >
              </b-form-textarea>
              <b-button variant="primary" @click="genDesc" :disabled="!element.canEdit" size="sm" class="mt-2"
                >Generate
              </b-button>
              <b-form-invalid-feedback :state="validDesc[0]">{{ validDesc[1] }}</b-form-invalid-feedback>
            </b-form-group>

            <b-form-group label="Notes" label-for="notes-input">
              <b-form-textarea
                id="notes-input"
                :disabled="!element.canEdit"
                v-model="element.notes"
                rows="3"
                max-rows="50"
              >
              </b-form-textarea>
              <b-form-invalid-feedback :state="validNotes[0]">{{ validNotes[1] }}</b-form-invalid-feedback>
            </b-form-group>
          </b-col>
        </b-row>

        <b-row>
          <b-col>
            <b-form-group label="Attributes">
              <b-row>
                <b-col xl="4">
                  <b-table-simple :responsive="true">
                    <b-thead>
                      <b-th></b-th>
                      <b-th>WS</b-th>
                      <b-th>BS</b-th>
                    </b-thead>
                    <b-tbody>
                      <b-tr>
                        <b-th>Rolls</b-th>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeRolls.WS"
                          >
                          </b-form-input>
                        </b-td>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeRolls.BS"
                          >
                          </b-form-input>
                        </b-td>
                      </b-tr>
                      <b-tr>
                        <b-th>Racial</b-th>
                        <b-td>{{ racial.WS }}</b-td>
                        <b-td>{{ racial.BS }}</b-td>
                      </b-tr>
                      <b-tr>
                        <b-th>Other</b-th>
                        <b-td>{{ element.modifiers.attributes.WS }}</b-td>
                        <b-td>{{ element.modifiers.attributes.BS }}</b-td>
                      </b-tr>
                      <b-tr>
                        <b-th>Adv</b-th>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeAdvances.WS"
                          >
                          </b-form-input>
                        </b-td>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeAdvances.BS"
                          >
                          </b-form-input>
                        </b-td>
                      </b-tr>
                      <b-tr>
                        <b-th>Total</b-th>
                        <b-td>{{ total.WS }}</b-td>
                        <b-td>{{ total.BS }}</b-td>
                      </b-tr>
                    </b-tbody>
                  </b-table-simple>
                </b-col>
                <b-col xl="4">
                  <b-table-simple :responsive="true">
                    <b-thead>
                      <b-th>S</b-th>
                      <b-th>T</b-th>
                      <b-th>I</b-th>
                      <b-th>Ag</b-th>
                    </b-thead>
                    <b-tbody>
                      <b-tr>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeRolls.S"
                          >
                          </b-form-input>
                        </b-td>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeRolls.T"
                          >
                          </b-form-input>
                        </b-td>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeRolls.I"
                          >
                          </b-form-input>
                        </b-td>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeRolls.Ag"
                          >
                          </b-form-input>
                        </b-td>
                      </b-tr>
                      <b-tr>
                        <b-td>{{ racial.S }}</b-td>
                        <b-td>{{ racial.T }}</b-td>
                        <b-td>{{ racial.I }}</b-td>
                        <b-td>{{ racial.Ag }}</b-td>
                      </b-tr>
                      <b-tr>
                        <b-td>{{ element.modifiers.attributes.S }}</b-td>
                        <b-td>{{ element.modifiers.attributes.T }}</b-td>
                        <b-td>{{ element.modifiers.attributes.I }}</b-td>
                        <b-td>{{ element.modifiers.attributes.Ag }}</b-td>
                      </b-tr>
                      <b-tr>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeAdvances.S"
                          >
                          </b-form-input>
                        </b-td>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeAdvances.T"
                          >
                          </b-form-input>
                        </b-td>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeAdvances.I"
                          >
                          </b-form-input>
                        </b-td>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeAdvances.Ag"
                          >
                          </b-form-input>
                        </b-td>
                      </b-tr>
                      <b-tr>
                        <b-td>{{ total.S }}</b-td>
                        <b-td>{{ total.T }}</b-td>
                        <b-td>{{ total.I }}</b-td>
                        <b-td>{{ total.Ag }}</b-td>
                      </b-tr>
                    </b-tbody>
                  </b-table-simple>
                </b-col>
                <b-col xl="4">
                  <b-table-simple :responsive="true">
                    <b-thead>
                      <b-th>Dex</b-th>
                      <b-th>Int</b-th>
                      <b-th>WP</b-th>
                      <b-th>Fel</b-th>
                    </b-thead>
                    <b-tbody>
                      <b-tr>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeRolls.Dex"
                          >
                          </b-form-input>
                        </b-td>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeRolls.Int"
                          >
                          </b-form-input>
                        </b-td>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeRolls.WP"
                          >
                          </b-form-input>
                        </b-td>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeRolls.Fel"
                          >
                          </b-form-input>
                        </b-td>
                      </b-tr>
                      <b-tr>
                        <b-td>{{ racial.Dex }}</b-td>
                        <b-td>{{ racial.Int }}</b-td>
                        <b-td>{{ racial.WP }}</b-td>
                        <b-td>{{ racial.Fel }}</b-td>
                      </b-tr>
                      <b-tr>
                        <b-td>{{ element.modifiers.attributes.Dex }}</b-td>
                        <b-td>{{ element.modifiers.attributes.Int }}</b-td>
                        <b-td>{{ element.modifiers.attributes.WP }}</b-td>
                        <b-td>{{ element.modifiers.attributes.Fel }}</b-td>
                      </b-tr>
                      <b-tr>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeAdvances.Dex"
                          >
                          </b-form-input>
                        </b-td>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeAdvances.Int"
                          >
                          </b-form-input>
                        </b-td>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeAdvances.WP"
                          >
                          </b-form-input>
                        </b-td>
                        <b-td>
                          <b-form-input
                            :disabled="!element.canEdit"
                            :number="true"
                            min="0"
                            max="99"
                            type="number"
                            v-model="element.attributeAdvances.Fel"
                          >
                          </b-form-input>
                        </b-td>
                      </b-tr>
                      <b-tr>
                        <b-td>{{ total.Dex }}</b-td>
                        <b-td>{{ total.Int }}</b-td>
                        <b-td>{{ total.WP }}</b-td>
                        <b-td>{{ total.Fel }}</b-td>
                      </b-tr>
                    </b-tbody>
                  </b-table-simple>
                </b-col>
              </b-row>
              <b-button variant="primary" size="sm" @click="genRolls" :disabled="!element.canEdit">
                Generate Rolls
              </b-button>
              <b-form-invalid-feedback :state="validBase">
                Invalid value of one or more Base (Roll + Racial + Other) Attributes. Base Attributes have to be between
                0 and 99.
              </b-form-invalid-feedback>
              <b-form-invalid-feedback :state="validAdv">
                Invalid value of one or more Attribute Advances. Attribute Advances have to be integers between 0 and
                99.
              </b-form-invalid-feedback>
              <b-form-invalid-feedback :state="validRoll">
                Invalid value of one or more Roll Attributes. Base Attributes have to be integers.
              </b-form-invalid-feedback>
            </b-form-group>
          </b-col>
        </b-row>

        <b-row>
          <b-col md="6">
            <b-form-group label="Skills">
              <CharacterSkillsTable
                :disabled="!element.canEdit"
                :characterSkills="initialSkills"
                :characterAtts="total"
                :speciesSkills="speciesSkills"
                :canSave="validAll"
                @listOfSkills="listOfSkills = $event"
                @selectedChanged="updateIdNumberList(element.skills, $event)"
                @stateChanged="validSkills = $event"
                @createNew="submitForm('skill')"
              ></CharacterSkillsTable>
              <b-form-invalid-feedback :state="validSkills">
                Invalid value of one or more Skills. Skills have to be integer numbers between 0 and 1000.
              </b-form-invalid-feedback>
            </b-form-group>
          </b-col>
          <b-col md="6">
            <b-form-group label="Talents">
              <CharacterTalentsTable
                :disabled="!element.canEdit"
                :characterTalents="initialTalents"
                :characterAtts="total"
                :speciesTalents="speciesTalents"
                :randomTalents="randomTalents"
                :canSave="validAll"
                @listOfTalents="listOfTalents = $event"
                @selectedChanged="updateIdNumberList(element.talents, $event)"
                @stateChanged="validTalents = $event"
                @createNew="submitForm('talent')"
                @modifiersChanged="talentModifiers = $event"
              ></CharacterTalentsTable>
              <b-form-invalid-feedback :state="validTalents">
                Invalid value of one or more Talents.
              </b-form-invalid-feedback>
            </b-form-group>
          </b-col>
        </b-row>

        <b-row>
          <b-col md="12">
            <b-form-group label="Trappings">
              <CharacterItemsTable
                :disabled="!element.canEdit"
                :canSave="validAll"
                :itemsEquipped="initialEquippedItems"
                :itemsCarried="initialCarriedItems"
                :itemsStored="initialStoredItems"
                :classItems="classItems"
                @equippedChanged="updateIdNumberList(element.equippedItems, $event)"
                @carriedChanged="updateIdNumberList(element.carriedItems, $event)"
                @storedChanged="updateIdNumberList(element.storedItems, $event)"
                @stateChanged="validItems = $event"
                @createNew="submitForm('item')"
              ></CharacterItemsTable>
              <b-form-invalid-feedback :state="validItems">
                Invalid number of one or more Items. Item quantity number has to be an integer between 0 and 1000.
              </b-form-invalid-feedback>
            </b-form-group>
          </b-col>
        </b-row>

        <b-row>
          <b-col md="6">
            <b-form-group label="Spells">
              <CharacterSpellsTable
                :disabled="!element.canEdit"
                :canSave="validAll"
                :selectedItems="initialSpells"
                @changed="updateIdList(element.spells, $event)"
                @createNew="submitForm('spell')"
              ></CharacterSpellsTable>
            </b-form-group>
          </b-col>

          <b-col md="6">
            <b-form-group label="Mutations">
              <CharacterMutationsTable
                :disabled="!element.canEdit"
                :canSave="validAll"
                :selectedItems="initialMutations"
                @changed="updateIdList(element.mutations, $event)"
                @createNew="submitForm('mutation')"
                @modifiersChanged="mutationModifiers = $event"
              ></CharacterMutationsTable>
            </b-form-group>
          </b-col>
        </b-row>

        <b-row>
          <b-col md="6">
            <b-form-group label="Prayers">
              <CharacterPrayersTable
                :disabled="!element.canEdit"
                :canSave="validAll"
                :selectedItems="initialPrayers"
                @changed="updateIdList(element.prayers, $event)"
                @createNew="submitForm('prayer')"
              ></CharacterPrayersTable>
            </b-form-group>
          </b-col>
        </b-row>

        <b-row>
          <b-col>
            <PublicElementBox v-if="element.canEdit" v-model="element.shared" elementName="Character" />

            <CreateSubmit
              :showAddAnother="showAddAnother"
              :disabled="!element.canEdit"
              :submitting="submitting"
              @goBack="goBack(true)"
              v-model="addAnother"
            ></CreateSubmit>
          </b-col>
        </b-row>
      </b-form>
    </b-container>
  </div>
</template>

<script>
import NavHelpers from "../../NavHelpers.vue";
import CreateElement from "../CreateElement.vue";
import CreateSubmit from "../CreateSubmit.vue";
import CharacterCareerTable from "./CharacterCareerTable.vue";
import CharacterSkillsTable from "./CharacterSkillsTable.vue";
import CharacterTalentsTable from "./CharacterTalentsTable.vue";
import CharacterItemsTable from "./CharacterItemsTable.vue";
import CharacterSpellsTable from "./CharacterSpellsTable.vue";
import CharacterPrayersTable from "./CharacterPrayersTable.vue";
import CharacterMutationsTable from "./CharacterMutationsTable.vue";
import PublicElementBox from "../PublicElementBox.vue";
import generateName from "../../../services/wh/characterGeneration/nameGeneration";
import generateDescription from "../../../services/wh/characterGeneration/descriptionGeneration";
import {
  generateCharacter,
  generateFateAndResilience,
} from "../../../services/wh/characterGeneration/characterGeneration";
import { generateRolls } from "../../../services/wh/characterGeneration/attGeneration";
import { authRequest } from "../../../services/auth";
import {
  generateEmptyCharacter,
  CharacterApi,
  getWounds,
  getMovement,
  getRacialAttributes,
  getTotalAttributes,
  getBaseAttributes,
  compareCharacter,
  generateNewCharacter,
  speciesWithRegionOptions,
  speciesWithRegionToSpecies,
} from "../../../services/wh/character";
import * as c from "../../../services/wh/characterConstants";
import { getCareerLevel, statusStandings, statusTiers } from "../../../services/wh/career";
import { generateEmptyModifiers, sumAndMultModifiers } from "../../../services/wh/characterModifiers";
import {
  validWhCharCoin,
  validWhCharExp,
  validWhCharSinCorr,
  validWhDesc,
  validWhFateResilience,
} from "../../../utils/validation/wh";

export default {
  name: "CreateCharacter",
  mixins: [CreateElement, NavHelpers],
  components: {
    CreateSubmit,
    CharacterCareerTable,
    CharacterSkillsTable,
    CharacterTalentsTable,
    CharacterItemsTable,
    CharacterSpellsTable,
    CharacterPrayersTable,
    CharacterMutationsTable,
    PublicElementBox,
  },
  data() {
    return {
      elementApi: new CharacterApi(authRequest),

      element: generateEmptyCharacter(),
      elementOriginal: generateEmptyCharacter(),

      speciesWithRegionsOptions: speciesWithRegionOptions(),

      statusOptions: Object.keys(statusTiers).map((key) => {
        return { value: parseInt(key), text: statusTiers[key] };
      }),

      standingOptions: Object.keys(statusStandings).map((key) => {
        return { value: parseInt(key), text: statusStandings[key] };
      }),

      validSkills: true,
      validTalents: true,
      validCareer: true,
      validItems: true,

      initialPastCareers: [],
      initialSkills: [],
      initialTalents: [],
      initialEquippedItems: [],
      initialCarriedItems: [],
      initialStoredItems: [],
      initialSpells: [],
      initialPrayers: [],
      initialMutations: [],

      selectedGenSpeciesWithRegion: c.HUMAN_REIKLAND,
      selectedGenCareer: -1,
      genLvl: false,
      genDetails: false,
      listOfCareers: [],
      listOfSkills: [],
      listOfTalents: [],
      createEnabled: true,
      generationProps: null,
      generationLevel: 1,

      talentModifiers: generateEmptyModifiers(),
      mutationModifiers: generateEmptyModifiers(),
    };
  },
  created() {
    this.elementType = "character";
    this.initializeElement();
    this.loadGenerationProps();
  },
  computed: {
    allDataLoaded() {
      return (
        !!this.generationProps &&
        !!this.listOfTalents.length &&
        !!this.listOfSkills.length &&
        !!this.listOfCareers.length
      );
    },
    classItems() {
      if (this.listOfCareers.length < 1 || !Object.hasOwn(this.element.career, "id")) {
        return {};
      } else {
        let selectedCareer = this.listOfCareers.find((x) => x.id === this.element.career.id);
        if (selectedCareer && this.generationProps && Object.hasOwn(this.generationProps, "classItems")) {
          return this.generationProps.classItems[selectedCareer.class];
        } else {
          return {};
        }
      }
    },
    speciesTalents() {
      if (this.generationProps && Object.hasOwn(this.generationProps, "speciesTalents")) {
        return this.generationProps.speciesTalents[this.element.speciesWithRegion];
      } else {
        return [];
      }
    },
    speciesSkills() {
      if (this.generationProps && Object.hasOwn(this.generationProps, "speciesSkills")) {
        return this.generationProps.speciesSkills[this.element.speciesWithRegion];
      } else {
        return [];
      }
    },
    randomTalents() {
      if (this.generationProps && Object.hasOwn(this.generationProps, "randomTalents")) {
        return this.generationProps.randomTalents;
      } else {
        return [];
      }
    },
    genCareers() {
      return this.generateCareers(false, this.selectedGenSpeciesWithRegion);
    },
    generateEnable() {
      return this.listOfCareers.length > 0;
    },
    wounds() {
      return getWounds(this.element);
    },
    movement() {
      return getMovement(this.element);
    },
    racial() {
      return getRacialAttributes(this.element);
    },
    total() {
      return getTotalAttributes(this.element);
    },
    base() {
      return getBaseAttributes(this.element);
    },
    validBase() {
      for (let value of Object.values(this.base)) {
        if (value > 99 || value < 0 || !Number.isInteger(value)) {
          return false;
        }
      }
      return true;
    },
    validAdv() {
      for (let value of Object.values(this.element.attributeAdvances)) {
        if (value > 99 || value < 0 || !Number.isInteger(value)) {
          return false;
        }
      }
      return true;
    },
    validRoll() {
      for (let value of Object.values(this.element.attributeRolls)) {
        if (!Number.isInteger(value)) {
          return false;
        }
      }
      return true;
    },
    validFate() {
      return validWhFateResilience(this.element.fate);
    },
    validFortune() {
      return validWhFateResilience(this.element.fortune);
    },
    validResilience() {
      return validWhFateResilience(this.element.resilience);
    },
    validResolve() {
      return validWhFateResilience(this.element.resolve);
    },
    validBrass() {
      return validWhCharCoin(this.element.brass);
    },
    validSilver() {
      return validWhCharCoin(this.element.silver);
    },
    validGold() {
      return validWhCharCoin(this.element.gold);
    },
    validCurrentExp() {
      return validWhCharExp(this.element.currentExp);
    },
    validSpentExp() {
      return validWhCharExp(this.element.spentExp);
    },
    validSin() {
      return validWhCharSinCorr(this.element.sin);
    },
    validCorruption() {
      return validWhCharSinCorr(this.element.corruption);
    },
    validNotes() {
      return validWhDesc(this.element.notes);
    },
    validAll() {
      return this.validate();
    },
  },
  methods: {
    setStatus() {
      let career = this.listOfCareers.find((x) => x.id === this.element.career.id);
      const lvl = this.element.career.number;
      const careerWithLevel = getCareerLevel(career, lvl);
      this.element.status = careerWithLevel.status;
      this.element.standing = careerWithLevel.standing;
    },
    setFateResilience() {
      [this.element.fate, this.element.resilience] = generateFateAndResilience(this.element.speciesWithRegion);
      this.element.fortune = this.element.fate;
      this.element.resolve = this.element.resilience;
    },
    generateCareers(includeRandom, speciesWithRegion) {
      let species = speciesWithRegionToSpecies(speciesWithRegion);
      let careers = this.listOfCareers
        .map((x, idx) => {
          let disabled = !x.species.includes(species);
          return { value: idx, text: x.name, disabled: disabled };
        })
        .filter((x) => x.disabled === false);

      careers.sort(function (x, y) {
        if (x.text === y.text) {
          return 0;
        } else {
          return x.text < y.text ? -1 : 1;
        }
      });

      if (includeRandom) {
        careers.unshift({
          value: -1,
          text: "Random (+50 XP)",
          disabled: false,
        });
      } else {
        careers.unshift({ value: -1, text: "Select Career", disabled: false });
      }

      return careers;
    },
    async loadGenerationProps() {
      let serverResp = null;
      try {
        serverResp = await this.callAndLogoutIfUnauthorized(authRequest.get)("/api/wh/generation");
        this.generationProps = serverResp.data.data;
      } catch (error) {
        this.addError();
      }
    },
    genCharacter(level, species, career) {
      let char = generateCharacter(
        species,
        career,
        this.listOfCareers,
        this.listOfSkills,
        this.listOfTalents,
        this.generationProps,
        level
      );
      Object.assign(this.element, char);
      this.resetTables();
    },
    genName() {
      this.element.name = generateName(this.element.speciesWithRegion, 2);
    },
    genDesc() {
      this.element.description = generateDescription(this.element.speciesWithRegion);
    },
    updateIdNumberList(idNumberList, newValue) {
      let item = idNumberList.find((x) => x.id === newValue.id);
      if (item) {
        if (newValue.number !== 0) {
          item.number = newValue.number;
        } else {
          idNumberList.splice(idNumberList.indexOf(item), 1);
        }
      } else {
        if (newValue !== 0) {
          idNumberList.push(newValue);
        }
      }
    },
    updateIdList(idList, newValue) {
      let item = idList.find((x) => x === newValue.id);
      if (item) {
        if (!newValue.selected) {
          idList.splice(idList.indexOf(item), 1);
        }
      } else {
        if (newValue.selected) {
          idList.push(newValue.id);
        }
      }
    },
    updatePastCareer(newValue) {
      let item = this.element.careerPath.find((x) => x.id === newValue.id && x.number === newValue.number);
      if (item) {
        if (!newValue.selected) {
          this.element.careerPath.splice(this.element.careerPath.indexOf(item), 1);
        }
      } else {
        if (newValue.selected) {
          this.element.careerPath.push({
            id: newValue.id,
            number: newValue.number,
          });
        }
      }
    },
    genRolls() {
      this.element.attributeRolls = generateRolls();
    },
    formModified() {
      return !compareCharacter(this.element, this.elementOriginal);
    },
    setElementToNew(canEdit) {
      this.element = generateNewCharacter(canEdit);
      this.elementOriginal = generateNewCharacter(canEdit);
    },
    resetTables() {
      this.initialPastCareers = JSON.parse(JSON.stringify(this.element.careerPath));
      this.initialSkills = JSON.parse(JSON.stringify(this.element.skills));
      this.initialTalents = JSON.parse(JSON.stringify(this.element.talents));
      this.initialEquippedItems = JSON.parse(JSON.stringify(this.element.equippedItems));
      this.initialCarriedItems = JSON.parse(JSON.stringify(this.element.carriedItems));
      this.initialStoredItems = JSON.parse(JSON.stringify(this.element.storedItems));
      this.initialSpells = JSON.parse(JSON.stringify(this.element.spells));
      this.initialPrayers = JSON.parse(JSON.stringify(this.element.prayers));
      this.initialMutations = JSON.parse(JSON.stringify(this.element.mutations));
    },
    validate() {
      return (
        this.validName[0] &&
        this.validDesc[0] &&
        this.validFate[0] &&
        this.validFortune[0] &&
        this.validResilience[0] &&
        this.validResolve[0] &&
        this.validBrass[0] &&
        this.validSilver[0] &&
        this.validGold[0] &&
        this.validCurrentExp[0] &&
        this.validSpentExp[0] &&
        this.validSin[0] &&
        this.validCorruption[0] &&
        this.validNotes[0] &&
        this.validBase &&
        this.validAdv &&
        this.validRoll &&
        this.validSkills &&
        this.validCareer &&
        this.validItems &&
        this.validTalents
      );
    },
  },
  watch: {
    selectedGenSpeciesWithRegion(newVal) {
      let species = speciesWithRegionToSpecies(newVal);
      if (this.selectedGenCareer > -1 && !this.listOfCareers[this.selectedGenCareer].species.includes(species)) {
        this.selectedGenCareer = -1;
      }
    },
    "element.career"(newVal, oldVal) {
      if (!Object.hasOwn(oldVal, "id")) {
        this.elementOriginal.career = { id: newVal.id, number: newVal.number };
      }
    },
    talentModifiers() {
      this.element.modifiers = sumAndMultModifiers([
        { multiplier: 1, modifiers: this.talentModifiers },
        { multiplier: 1, modifiers: this.mutationModifiers },
      ]);
    },
    mutationModifiers() {
      this.element.modifiers = sumAndMultModifiers([
        { multiplier: 1, modifiers: this.talentModifiers },
        { multiplier: 1, modifiers: this.mutationModifiers },
      ]);
    },
  },
};
</script>

<style scoped></style>
