import { SpeciesWithRegion } from "../services/wh/characterUtils.ts";
import { apiResponseToCharacterFull, CharacterFull, CharacterFullApiData } from "../services/wh/characterFull.ts";
import { CareerClass, StatusTier } from "../services/wh/career.ts";
import { AttributeName } from "../services/wh/attributes.ts";
import {
  AmmoGroup,
  ArmourGroup,
  ArmourLocation,
  Availability,
  CarryType,
  ItemType,
  MeleeGroup,
  MeleeReach,
  RangedGroup,
  WeaponHands,
} from "../services/wh/item.ts";
import { ItemPropertyType } from "../services/wh/itemproperty.ts";
import { expect, test } from "vitest";
import { ApiResponse } from "../services/wh/common.ts";

const characterFullApiData: CharacterFullApiData = {
  name: "charDisplay",
  species: SpeciesWithRegion.WoodElfDefault,
  fate: 1,
  fortune: 2,
  resilience: 3,
  resolve: 4,
  brass: 12,
  silver: 5,
  gold: 1,
  spentExp: 1000,
  currentExp: 230,
  status: 1,
  standing: 2,
  description: "character display",
  notes: "asd",
  careerPath: [
    {
      number: 1,
      wh: {
        id: "id1",
        canEdit: true,
        ownerId: "owner",
        object: {
          name: "career_1",
          description: "",
          species: [],
          shared: true,
          source: {},
          class: CareerClass.Academic,
          level1: {
            name: "career_1_level_1",
            status: StatusTier.Gold,
            standing: 1,
            skills: [],
            talents: [],
            attributes: [],
            items: "",
          },
          level2: {
            name: "career_2_level_2",
            status: StatusTier.Gold,
            standing: 1,
            skills: [],
            talents: [],
            attributes: [],
            items: "",
          },
          level3: {
            name: "career_3_level_3",
            status: StatusTier.Gold,
            standing: 1,
            skills: [],
            talents: [],
            attributes: [],
            items: "",
          },
          level4: {
            name: "career_4_level_4",
            status: StatusTier.Gold,
            standing: 1,
            skills: [],
            talents: [],
            attributes: [],
            items: "",
          },
        },
      },
    },
    {
      number: 2,
      wh: {
        id: "id2",
        canEdit: true,
        ownerId: "owner",
        object: {
          name: "career_2",
          description: "",
          species: [],
          shared: true,
          source: {},
          class: CareerClass.Courtier,
          level1: {
            name: "career_2_level_1",
            status: StatusTier.Gold,
            standing: 1,
            skills: [],
            talents: [],
            attributes: [],
            items: "",
          },
          level2: {
            name: "career_2_level_2",
            status: StatusTier.Gold,
            standing: 1,
            skills: [],
            talents: [],
            attributes: [],
            items: "",
          },
          level3: {
            name: "career_2_level_3",
            status: StatusTier.Gold,
            standing: 1,
            skills: [],
            talents: [],
            attributes: [],
            items: "",
          },
          level4: {
            name: "career_2_level_4",
            status: StatusTier.Gold,
            standing: 1,
            skills: [],
            talents: [],
            attributes: [],
            items: "",
          },
        },
      },
    },
  ],
  career: {
    number: 3,
    wh: {
      id: "id3",
      canEdit: true,
      ownerId: "owner",
      object: {
        name: "career_3",
        class: CareerClass.Peasant,
        description: "",
        species: [],
        shared: true,
        source: {},
        level1: {
          name: "career_3_level_1",
          status: StatusTier.Gold,
          standing: 1,
          skills: [],
          talents: [],
          attributes: [],
          items: "",
        },
        level2: {
          name: "career_3_level_2",
          status: StatusTier.Gold,
          standing: 1,
          skills: [],
          talents: [],
          attributes: [],
          items: "",
        },
        level3: {
          name: "career_3_level_3",
          status: StatusTier.Gold,
          standing: 1,
          skills: [],
          talents: [],
          attributes: [],
          items: "",
        },
        level4: {
          name: "career_3_level_4",
          status: StatusTier.Gold,
          standing: 1,
          skills: [],
          talents: [],
          attributes: [],
          items: "",
        },
      },
    },
  },
  baseAttributes: { WS: 40, BS: 40, S: 30, T: 25, I: 50, Ag: 35, Dex: 50, Int: 35, WP: 35, Fel: 25 },
  attributeAdvances: { WS: 1, BS: 2, S: 3, T: 0, I: 0, Ag: 0, Dex: 0, Int: 0, WP: 0, Fel: 0 },
  skills: [
    {
      wh: {
        id: "id4",
        canEdit: true,
        ownerId: "owner",
        object: {
          name: "basic",
          isGroup: true,
          attribute: 3,
          type: 0,
          description: "",
          displayZero: true,
          group: [],
          shared: true,
          source: {},
        },
      },
      number: 4,
    },
    {
      wh: {
        id: "id5",
        canEdit: true,
        ownerId: "owner",
        object: {
          name: "advanced",
          isGroup: false,
          attribute: 1,
          type: 1,
          description: "",
          displayZero: true,
          group: [],
          shared: true,
          source: {},
        },
      },
      number: 5,
    },
  ],
  talents: [
    {
      number: 6,
      wh: {
        id: "id6",
        canEdit: true,
        ownerId: "owner",
        object: {
          name: "talent_1",
          modifiers: {
            size: 0,
            attributes: { WS: 1, BS: 2, S: 3, T: 0, I: 0, Ag: 0, Dex: 0, Int: 0, WP: 0, Fel: 0 },
            movement: 0,
          },
          description: "",
          tests: "",
          group: [],
          isGroup: false,
          maxRank: 1,
          attribute: AttributeName.Int,
          shared: true,
          source: {},
        },
      },
    },
    {
      number: 6,
      wh: {
        id: "id7",
        canEdit: true,
        ownerId: "owner",
        object: {
          name: "talent_2",
          modifiers: {
            size: 0,
            attributes: { WS: 0, BS: 0, S: 0, T: 0, I: 0, Ag: 0, Dex: 0, Int: 0, WP: 0, Fel: 1 },
            movement: 0,
          },
          description: "",
          tests: "",
          group: [],
          isGroup: false,
          maxRank: 1,
          attribute: AttributeName.Int,
          shared: true,
          source: {},
        },
      },
    },
    {
      number: 1,
      wh: {
        id: "id8",
        canEdit: true,
        ownerId: "owner",
        object: {
          name: "talent_3",
          modifiers: {
            size: -1,
            attributes: { WS: 0, BS: 0, S: 0, T: 0, I: 0, Ag: 0, Dex: 0, Int: 0, WP: 0, Fel: 0 },
            movement: 1,
          },
          description: "",
          tests: "",
          group: [],
          isGroup: false,
          maxRank: 1,
          attribute: AttributeName.Int,
          shared: true,
          source: {},
        },
      },
    },
  ],
  equippedItems: [
    {
      number: 1,
      wh: {
        id: "id9",
        canEdit: true,
        ownerId: "owner",
        object: {
          name: "item_1",
          enc: 1.5,
          type: ItemType.Melee,
          melee: {
            group: MeleeGroup.Basic,
            reach: MeleeReach.Short,
            dmg: 2,
            dmgSbMult: 2,
            hands: WeaponHands.OneHanded,
          },
          ranged: {
            hands: WeaponHands.OneHanded,
            dmg: 0,
            dmgSbMult: 0,
            rng: 0,
            rngSbMult: 0,
            group: RangedGroup.Bow,
          },
          ammunition: { dmg: 0, rng: 0, rngMult: 0, group: AmmoGroup.Bow },
          armour: { points: 0, location: [], group: ArmourGroup.SoftLeather },
          grimoire: { spells: [] },
          container: { capacity: 1, carryType: CarryType.NotCarriableAndNotWearable },
          other: { carryType: CarryType.NotCarriableAndNotWearable },
          properties: [
            {
              id: "pid1",
              canEdit: true,
              ownerId: "owner",
              object: {
                name: "item_1_property_1",
                description: "",
                type: ItemPropertyType.Quality,
                applicableTo: [],
                shared: true,
                source: {},
              },
            },
          ],
          description: "item_1_desc",
          price: 0,
          availability: Availability.Common,
          shared: true,
          source: {},
        },
      },
    },
    {
      number: 2,
      wh: {
        id: "id10",
        canEdit: true,
        ownerId: "owner",
        object: {
          name: "item_2",
          enc: 1,
          type: ItemType.Ranged,
          melee: {
            hands: WeaponHands.OneHanded,
            dmg: 0,
            dmgSbMult: 0,
            reach: MeleeReach.Personal,
            group: MeleeGroup.Basic,
          },
          ranged: {
            group: RangedGroup.Bow,
            rng: 10,
            rngSbMult: 1.5,
            dmg: 2,
            dmgSbMult: 1.2,
            hands: WeaponHands.TwoHanded,
          },
          ammunition: { dmg: 0, rng: 0, rngMult: 0, group: AmmoGroup.Bow },
          armour: { points: 0, location: [], group: ArmourGroup.SoftLeather },
          grimoire: { spells: [] },
          container: { capacity: 1, carryType: CarryType.NotCarriableAndNotWearable },
          other: { carryType: CarryType.NotCarriableAndNotWearable },
          properties: [
            {
              id: "pid2",
              canEdit: true,
              ownerId: "owner",
              object: {
                name: "item_2_property_1",
                description: "",
                type: ItemPropertyType.Quality,
                applicableTo: [],
                shared: true,
                source: {},
              },
            },
            {
              id: "pid3",
              canEdit: true,
              ownerId: "owner",
              object: {
                name: "item_2_property_2",
                description: "",
                type: ItemPropertyType.Quality,
                applicableTo: [],
                shared: true,
                source: {},
              },
            },
          ],
          description: "item_2_desc",
          price: 0,
          availability: Availability.Common,
          shared: true,
          source: {},
        },
      },
    },
    {
      number: 3,
      wh: {
        id: "id11",
        canEdit: true,
        ownerId: "owner",
        object: {
          name: "item_3",
          enc: 0.5,
          type: ItemType.Ammunition,
          melee: {
            hands: WeaponHands.OneHanded,
            dmg: 0,
            dmgSbMult: 0,
            reach: MeleeReach.Personal,
            group: MeleeGroup.Basic,
          },
          ranged: {
            hands: WeaponHands.OneHanded,
            dmg: 0,
            dmgSbMult: 0,
            rng: 0,
            rngSbMult: 0,
            group: RangedGroup.Bow,
          },
          ammunition: { group: AmmoGroup.Bow, dmg: 1, rng: 5, rngMult: 1.3 },
          armour: { points: 0, location: [], group: ArmourGroup.SoftLeather },
          grimoire: { spells: [] },
          container: { capacity: 1, carryType: CarryType.NotCarriableAndNotWearable },
          other: { carryType: CarryType.NotCarriableAndNotWearable },
          properties: [],
          description: "item_3_desc",
          price: 0,
          availability: Availability.Common,
          shared: true,
          source: {},
        },
      },
    },
    {
      number: 3,
      wh: {
        id: "id12",
        canEdit: true,
        ownerId: "owner",
        object: {
          name: "item_4",
          enc: 2,
          type: ItemType.Armour,
          melee: {
            group: MeleeGroup.Basic,
            reach: MeleeReach.Short,
            dmg: 2,
            dmgSbMult: 2,
            hands: WeaponHands.OneHanded,
          },
          ranged: {
            hands: WeaponHands.OneHanded,
            dmg: 0,
            dmgSbMult: 0,
            rng: 0,
            rngSbMult: 0,
            group: RangedGroup.Bow,
          },
          ammunition: { dmg: 0, rng: 0, rngMult: 0, group: AmmoGroup.Bow },
          armour: { group: ArmourGroup.BoiledLeather, points: 2, location: [ArmourLocation.Body, ArmourLocation.Head] },
          grimoire: { spells: [] },
          container: { capacity: 1, carryType: CarryType.NotCarriableAndNotWearable },
          other: { carryType: CarryType.NotCarriableAndNotWearable },
          properties: [
            {
              id: "pid4",
              canEdit: true,
              ownerId: "owner",
              object: {
                name: "item_4_property_1",
                description: "",
                type: ItemPropertyType.Quality,
                applicableTo: [],
                shared: true,
                source: {},
              },
            },
          ],
          description: "item_4_desc",
          price: 0,
          availability: Availability.Common,
          shared: true,
          source: {},
        },
      },
    },
  ],
  carriedItems: [
    {
      number: 1,
      wh: {
        id: "id13",
        canEdit: true,
        ownerId: "owner",
        object: {
          name: "item_5",
          enc: 2,
          type: ItemType.Container,
          melee: {
            hands: WeaponHands.OneHanded,
            dmg: 0,
            dmgSbMult: 0,
            reach: MeleeReach.Personal,
            group: MeleeGroup.Basic,
          },
          ranged: {
            hands: WeaponHands.OneHanded,
            dmg: 0,
            dmgSbMult: 0,
            rng: 0,
            rngSbMult: 0,
            group: RangedGroup.Bow,
          },
          ammunition: { dmg: 0, rng: 0, rngMult: 0, group: AmmoGroup.Bow },
          armour: { points: 0, location: [], group: ArmourGroup.SoftLeather },
          grimoire: { spells: [] },
          container: { capacity: 2, carryType: 0 },
          other: { carryType: CarryType.NotCarriableAndNotWearable },
          properties: [
            {
              id: "pid5",
              canEdit: true,
              ownerId: "owner",
              object: {
                name: "item_5_property_1",
                description: "",
                type: ItemPropertyType.Quality,
                applicableTo: [],
                shared: true,
                source: {},
              },
            },
            {
              id: "pid6",
              canEdit: true,
              ownerId: "owner",
              object: {
                name: "item_5_property_2",
                description: "",
                type: ItemPropertyType.Quality,
                applicableTo: [],
                shared: true,
                source: {},
              },
            },
          ],
          description: "item_5_desc",
          price: 0,
          availability: Availability.Common,
          shared: true,
          source: {},
        },
      },
    },
    {
      number: 2,
      wh: {
        id: "id14",
        canEdit: true,
        ownerId: "owner",
        object: {
          name: "item_6",
          enc: 0,
          type: ItemType.Other,
          melee: {
            hands: WeaponHands.OneHanded,
            dmg: 0,
            dmgSbMult: 0,
            reach: MeleeReach.Personal,
            group: MeleeGroup.Basic,
          },
          ranged: {
            hands: WeaponHands.OneHanded,
            dmg: 0,
            dmgSbMult: 0,
            rng: 0,
            rngSbMult: 0,
            group: RangedGroup.Bow,
          },
          ammunition: { dmg: 0, rng: 0, rngMult: 0, group: AmmoGroup.Bow },
          armour: { points: 0, location: [], group: ArmourGroup.SoftLeather },
          grimoire: { spells: [] },
          container: { capacity: 0, carryType: 0 },
          other: { carryType: 1 },
          properties: [],
          description: "item_6_desc",
          price: 0,
          availability: Availability.Common,
          shared: true,
          source: {},
        },
      },
    },
    {
      number: 1,
      wh: {
        id: "id14a",
        canEdit: true,
        ownerId: "owner",
        object: {
          name: "spellbook",
          enc: 1,
          type: ItemType.Grimoire,
          melee: {
            hands: WeaponHands.OneHanded,
            dmg: 0,
            dmgSbMult: 0,
            reach: MeleeReach.Personal,
            group: MeleeGroup.Basic,
          },
          ranged: {
            hands: WeaponHands.OneHanded,
            dmg: 0,
            dmgSbMult: 0,
            rng: 0,
            rngSbMult: 0,
            group: RangedGroup.Bow,
          },
          ammunition: { dmg: 0, rng: 0, rngMult: 0, group: AmmoGroup.Bow },
          armour: { points: 0, location: [], group: ArmourGroup.SoftLeather },
          grimoire: {
            spells: [
              {
                id: "sid1",
                canEdit: true,
                ownerId: "owner",
                object: {
                  name: "spellbook_spell_1",
                  range: "spellbook_spell_1_range",
                  target: "spellbook_spell_1_target",
                  duration: "spellbook_spell_1_duration",
                  description: "spellbook_spell_1_desc",
                  cn: 1,
                  shared: true,
                  source: {},
                },
              },
              {
                id: "sid2",
                canEdit: true,
                ownerId: "owner",
                object: {
                  name: "spellbook_spell_2",
                  range: "spellbook_spell_2_range",
                  target: "spellbook_spell_2_target",
                  duration: "spellbook_spell_2_duration",
                  description: "spellbook_spell_2_desc",
                  cn: 2,
                  shared: true,
                  source: {},
                },
              },
            ],
          },
          container: { capacity: 0, carryType: 0 },
          other: { carryType: 0 },
          properties: [],
          description: "spellbook_desc",
          price: 0,
          availability: Availability.Common,
          shared: true,
          source: {},
        },
      },
    },
  ],
  storedItems: [
    {
      number: 5,
      wh: {
        id: "id15",
        canEdit: true,
        ownerId: "owner",
        object: {
          name: "item_7",
          enc: 7,
          type: ItemType.Other,
          melee: {
            hands: WeaponHands.OneHanded,
            dmg: 0,
            dmgSbMult: 0,
            reach: MeleeReach.Personal,
            group: MeleeGroup.Basic,
          },
          ranged: {
            hands: WeaponHands.OneHanded,
            dmg: 0,
            dmgSbMult: 0,
            rng: 0,
            rngSbMult: 0,
            group: RangedGroup.Bow,
          },
          ammunition: { dmg: 0, rng: 0, rngMult: 0, group: AmmoGroup.Bow },
          armour: { points: 0, location: [], group: ArmourGroup.SoftLeather },
          grimoire: { spells: [] },
          container: { capacity: 0, carryType: 0 },
          other: { carryType: 2 },
          properties: [],
          description: "item_7_desc",
          price: 0,
          availability: Availability.Common,
          shared: true,
          source: {},
        },
      },
    },
  ],
  spells: [
    {
      id: "id16",
      canEdit: true,
      ownerId: "owner",
      object: {
        name: "spell_1",
        range: "spell_1_range",
        target: "spell_1_target",
        duration: "spell_1_duration",
        description: "spell_1_desc",
        cn: 1,
        shared: true,
        source: {},
      },
    },
    {
      id: "id17",
      canEdit: true,
      ownerId: "owner",
      object: {
        name: "spell_2",
        range: "spell_2_range",
        target: "spell_2_target",
        duration: "spell_2_duration",
        description: "spell_2_desc",
        cn: 2,
        shared: true,
        source: {},
      },
    },
  ],
  prayers: [
    {
      id: "id16a",
      canEdit: true,
      ownerId: "owner",
      object: {
        name: "prayer_1",
        range: "prayer_1_range",
        target: "prayer_1_target",
        duration: "prayer_1_duration",
        description: "prayer_1_desc",
        shared: true,
        source: {},
      },
    },
    {
      id: "id17a",
      canEdit: true,
      ownerId: "owner",
      object: {
        name: "prayer_2",
        range: "prayer_2_range",
        target: "prayer_2_target",
        duration: "prayer_2_duration",
        description: "prayer_2_desc",
        shared: true,
        source: {},
      },
    },
  ],
  sin: 1,
  corruption: 2,
  mutations: [
    {
      id: "id18",
      canEdit: true,
      ownerId: "owner",
      object: {
        name: "mut_1",
        type: 0,
        description: "mut_1_desc",
        modifiers: {
          size: -1,
          attributes: { WS: 0, BS: 0, S: 0, T: 0, I: 0, Ag: 0, Dex: 0, Int: 2, WP: 2, Fel: 2 },
          movement: 1,
        },
        shared: true,
        source: {},
      },
    },
    {
      id: "id19",
      canEdit: true,
      ownerId: "owner",
      object: {
        name: "mut_2",
        type: 1,
        description: "mut_2_desc",
        modifiers: {
          size: 1,
          attributes: { WS: 0, BS: 0, S: 0, T: 0, I: 0, Ag: 0, Dex: 0, Int: 0, WP: 0, Fel: 0 },
          movement: 0,
        },
        shared: true,
        source: {},
      },
    },
  ],
  shared: true,
};

const characterFullApiResponse: ApiResponse<CharacterFullApiData> = {
  id: "id",
  canEdit: true,
  ownerId: "owner",
  object: characterFullApiData,
};

const characterFull = {
  id: "id",
  name: "charDisplay",
  species: "Wood Elf",
  fate: 1,
  fortune: 2,
  resilience: 3,
  resolve: 4,
  brass: 12,
  silver: 5,
  gold: 1,
  spentExp: 1000,
  currentExp: 230,
  totalExp: 1230,
  status: "Silver",
  standing: 2,
  description: "character display",
  notes: "asd",
  sin: 1,
  corruption: 2,
  shared: true,
  canEdit: true,
  careerName: "career_3 3",
  careerLevelName: "career_3_level_3",
  className: "Peasant",
  pastCareers: ["career_1 1", "career_2 2"],
  baseAttributes: { WS: 40, BS: 40, S: 30, T: 25, I: 50, Ag: 35, Dex: 50, Int: 35, WP: 35, Fel: 25 },
  attributeAdvances: { WS: 1, BS: 2, S: 3, T: 0, I: 0, Ag: 0, Dex: 0, Int: 0, WP: 0, Fel: 0 },
  otherAttributes: { WS: 6, BS: 12, S: 18, T: 0, I: 0, Ag: 0, Dex: 0, Int: 2, WP: 2, Fel: 8 },
  attributes: { Ag: 35, BS: 54, Dex: 50, Fel: 33, I: 50, Int: 37, S: 51, T: 25, WP: 37, WS: 47 },
  movement: 7,
  walk: 14,
  run: 28,
  wounds: 7,
  talents: [
    { name: "talent_1", rank: 6 },
    { name: "talent_2", rank: 6 },
    { name: "talent_3", rank: 1 },
  ],
  basicSkills: [
    {
      name: "basic (Any)",
      attributeName: "S",
      attributeValue: 51,
      advances: 4,
      skill: 55,
    },
  ],
  advancedSkills: [
    {
      name: "advanced",
      attributeName: "WS",
      attributeValue: 47,
      advances: 5,
      skill: 52,
    },
  ],
  equippedArmor: [
    {
      name: "item_4",
      enc: 2,
      qualitiesFlawsRunes: ["item_4_property_1"],
      number: 3,
      description: "item_4_desc",
      type: "Armour",
      group: "Boiled leather",
      locations: ["Body", "Head"],
      ap: 2,
    },
  ],
  equippedWeapon: [
    {
      name: "item_1",
      enc: 1.5,
      qualitiesFlawsRunes: ["item_1_property_1"],
      number: 1,
      description: "item_1_desc",
      type: "Melee",
      group: "Basic",
      rng: "Short",
      dmg: "12",
    },
    {
      name: "item_2",
      enc: 1,
      qualitiesFlawsRunes: ["item_2_property_1", "item_2_property_2"],
      number: 2,
      description: "item_2_desc",
      type: "Ranged",
      group: "Bow",
      rng: "17.5",
      dmg: "8",
    },
    {
      name: "item_3",
      enc: 0.5,
      qualitiesFlawsRunes: [],
      number: 3,
      description: "item_3_desc",
      type: "Ammunition",
      group: "Bow",
      rng: "Weapon x1.3+5",
      dmg: "Weapon+1",
    },
  ],
  equippedOther: [],
  carried: [
    {
      name: "item_5",
      enc: 2,
      qualitiesFlawsRunes: ["item_5_property_1", "item_5_property_2"],
      number: 1,
      description: "(Capacity 2) item_5_desc",
      type: "Container",
    },
    {
      name: "item_6",
      enc: 0,
      qualitiesFlawsRunes: [],
      number: 2,
      description: "item_6_desc",
      type: "Other",
    },
    {
      number: 1,
      name: "spellbook",
      enc: 1,
      qualitiesFlawsRunes: [],
      description: "spellbook_desc",
      type: "Grimoire",
      spells: [
        {
          name: "spellbook_spell_1",
          range: "spellbook_spell_1_range",
          target: "spellbook_spell_1_target",
          duration: "spellbook_spell_1_duration",
          description: "spellbook_spell_1_desc",
          cn: 1,
        },
        {
          name: "spellbook_spell_2",
          range: "spellbook_spell_2_range",
          target: "spellbook_spell_2_target",
          duration: "spellbook_spell_2_duration",
          description: "spellbook_spell_2_desc",
          cn: 2,
        },
      ],
    },
  ],
  stored: [{ name: "item_7", enc: 7, qualitiesFlawsRunes: [], number: 5, description: "item_7_desc", type: "Other" }],
  spells: [
    {
      name: "spell_1",
      range: "spell_1_range",
      target: "spell_1_target",
      duration: "spell_1_duration",
      description: "spell_1_desc",
      cn: 1,
    },
    {
      name: "spell_2",
      range: "spell_2_range",
      target: "spell_2_target",
      duration: "spell_2_duration",
      description: "spell_2_desc",
      cn: 2,
    },
  ],
  prayers: [
    {
      name: "prayer_1",
      range: "prayer_1_range",
      target: "prayer_1_target",
      duration: "prayer_1_duration",
      description: "prayer_1_desc",
    },
    {
      name: "prayer_2",
      range: "prayer_2_range",
      target: "prayer_2_target",
      duration: "prayer_2_duration",
      description: "prayer_2_desc",
    },
  ],
  mutations: [
    { name: "mut_1", type: "Physical", description: "mut_1_desc" },
    { name: "mut_2", type: "Mental", description: "mut_2_desc" },
  ],
  encWeapon: 5,
  encArmor: 3,
  encOther: 0,
  encCarried: 3,
} as CharacterFull;

test("apiResponseToCharacterFull returns expected item", () => {
  expect(apiResponseToCharacterFull(characterFullApiResponse)).toMatchObject(characterFull);
});
