# Default values for hammergen.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: hammergen

replicaCount: 1

image:
  repository: "dirac1234/hammergen"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

config:
  access_token_expires_minutes: 120
  refresh_token_expires_days: 1

secrets:
  create: true
  flask_secret_key: "flask_secret_key"
  mongo_uri: "mongo_uri"
  sendgrid_api_key: "sendgrid_api_key"
  recaptcha_secret: "recaptcha_secret"

webserver:
  replicaCount: 1

  image:
    repository: "nginx"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.21"

  distImage:
    repository: "dirac1234/hammergen_dist"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  podAnnotations: { }
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

  service:
    serviceType: ClusterIP
    nodePort:

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: ImplementationSpecific