FROM python:3.8.2-slim-buster

RUN addgroup --system appusergroup && adduser --system appuser && usermod -G appusergroup appuser

WORKDIR /app
COPY api ./api
COPY requirements_docker_build.txt ./requirements.txt

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

RUN chown -R appuser:appusergroup /app
USER appuser

CMD bash -c "gunicorn --threads 8 --workers 1 --timeout 0 -k gthread -b 0.0.0.0:5000 api:create_app\(\)"
