apiVersion: apps/v1
kind: Deployment
metadata:
  name: hammergen
  labels:
    app: hammergen
  namespace: hammergen-{{ ENV }}
spec:
  replicas: 2
  progressDeadlineSeconds: 120
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hammergen
  template:
    metadata:
      name: hammergen
      labels:
        app: hammergen
    spec:
      restartPolicy: Always
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-config
            - mountPath: /app/static
              name: static
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: static
          emptyDir: { }