version: "3.7"

services:
  web:
    build:
      context: ../../../services/web
      args:
        build: build_container_staging
    image: dirac1234/hammergen_web
    volumes:
      - static_volume:/app/static
    restart: always
    expose:
      - 5000
    env_file:
      - ../../../services/web/.env
      - ../../../services/web/.env.secrets.staging
  nginx:
    build: ../../../services/nginx
    image: dirac1234/hammergen_nginx
    volumes:
      - static_volume:/app/static
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume: