version: "3.7"

services:
  dist:
    build:
      context: ../../../src
      dockerfile: Dockerfile_build_dist
    volumes:
      - static_volume:/dist
  web:
    build:
      context: ../../../src
    restart: always
    expose:
      - 5000
    ports:
      - "5000:5000"
    env_file:
      - .env
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/dist
    restart: always
    ports:
      - "80:80"
    depends_on:
      - dist
      - web

volumes:
  static_volume: