FROM node:18.12.1
ARG build=build_container_staging

WORKDIR /frontend
COPY ./frontend/public ./public
COPY ./frontend/src ./src
COPY ./frontend/.eslintrc.cjs .
COPY ./frontend/index.html .
COPY ./frontend/package.json .
COPY ./frontend/vite.config.js .

RUN npm install && npm run-script $build && rm -r node_modules

RUN mkdir /dist

CMD bash -c "cp -r /frontend/dist/* /dist"
