FROM node:24-alpine
ARG build=build_container_staging

WORKDIR /frontend
ADD ./frontend /frontend
RUN rm -rf dist node_modules
RUN npm ci && npm run $build && rm -rf node_modules

RUN mkdir /dist

CMD ["sh", "-c", "cp -r /frontend/dist/* /dist"]

