version: '3.9'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017

  wfrp:
    container_name: wfrp-mongodb
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HAMMERGEN_SERVICES_EMAIL: "mockemail"
      HAMMERGEN_SERVICES_CAPTCHA: "mockcaptcha"
      HAMMERGEN_USERSERVICE_CREATE_MOCKS: "true"
      HAMMERGEN_WHSERVICE_CREATE_MOCKS: "true"
      HAMMERGEN_MONGODB_CREATE_USER_INDEXES: "true"
      HAMMERGEN_MONGODB_URI: "mongodb://admin:admin@mongodb:27017/"
    ports:
      - 8081:8080
    depends_on:
      - mongodb

  wfrp-memdb:
    container_name: wfrp-memdb
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HAMMERGEN_SERVICES_EMAIL: "mockemail"
      HAMMERGEN_SERVICES_CAPTCHA: "mockcaptcha"
      HAMMERGEN_SERVICES_DB: "memdb"
      HAMMERGEN_USERSERVICE_CREATE_MOCKS: "true"
      HAMMERGEN_WHSERVICE_CREATE_MOCKS: "true"
    ports:
      - 8082:8080
