FROM node:18.12.1
ARG build=build_container_staging

WORKDIR /frontend
ADD ./frontend /frontend
RUN rm -rf dist node_modules
RUN npm install && npm run-script $build && rm -r node_modules

RUN mkdir /dist

CMD bash -c "cp -r /frontend/dist/* /dist"
