apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-tls-certificate
spec:
  secretName: tls-certificate
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  duration: 8760h   # 365 days
  renewBefore: 720h # 30 days
  commonName: "*.mongodb-svc.mongodb.svc.cluster.local"
  dnsNames:
    - "*.mongodb-svc.mongodb.svc.cluster.local"