{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hammergen.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hammergen.labels" . | nindent 4 }}
type: Opaque
data:
  flask_secret_key: {{ .Values.secrets.flask_secret_key | b64enc }}
  mongo_uri: {{ .Values.secrets.mongo_uri | b64enc }}
  sendgrid_api_key: {{ .Values.secrets.sendgrid_api_key | b64enc }}
  recaptcha_secret: {{ .Values.secrets.recaptcha_secret | b64enc }}
{{- end }}
