apiVersion: v1
kind: Service
metadata:
  name: {{ include "hammergen.fullname" . }}
  labels:
    {{- include "hammergen.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hammergen.selectorLabels" . | nindent 4 }}
