apiVersion: v1
kind: Service
metadata:
  name: {{ include "hammergen.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "hammergen.name" . }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "hammergen.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 5000
      targetPort: 5000