apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webserver.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "webserver.name" . }}
spec:
  replicas: {{ .Values.webserver.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "webserver.name" . }}
{{- /* app.kubernetes.io/instance is included in common.labels  */}}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.webserver.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/name: {{ include "webserver.name" . }}
    spec:
      restartPolicy: Always
      containers:
        - name: webserver
          image: "{{ .Values.webserver.image.repository }}:{{ .Values.webserver.image.tag }}"
          imagePullPolicy: {{ .Values.webserver.image.pullPolicy }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-config
            - mountPath: /dist
              name: dist
      {{- with .Values.webserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: dist
          image: "{{ .Values.webserver.distImage.repository }}:{{ .Values.webserver.distImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.webserver.distImage.pullPolicy }}
          volumeMounts:
            - mountPath: /dist
              name: dist
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "webserver.fullname" . }}
        - name: dist
          emptyDir: { }