  name: deploy-frontend
  on:
    push:
      branches:
        - main
  jobs:
    hello-world:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - run: bash hello.sh
