name: deploy-backend
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          project_id: hammergen-337809
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HAMMERGEN_337809 }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Docker
        run: gcloud auth configure-docker ${{ vars.AR_REGISTRY }} --quiet

      - name: Build image
        run: cd ./src && docker build -t ${{ vars.AR_REGISTRY }}/${{ vars.PROJECT_ID }}/main/hammergen:${{ inputs.environment }} .

      - name: Push image
        run: cd ./src && docker push ${{ vars.AR_REGISTRY }}/${{ vars.PROJECT_ID }}/main/hammergen:${{ inputs.environment }}

      - name: Deploy to cloud run
        run: gcloud run deploy hammergen-${{ inputs.environment }} --region=${{ vars.REGION }} --project=${{ vars.PROJECT_ID }} --image=${{ vars.AR_REGISTRY }}/${{ vars.PROJECT_ID }}/main/hammergen:${{ inputs.environment }} --allow-unauthenticated --concurrency=${{ vars.CONCURRENCY }}
