name: Lint and test

on:
  pull_request:
    branches:
      - "*"

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./src/frontend/package-lock.json"

      - name: Install dependencies
        working-directory: ./src/frontend
        run: npm ci

      - name: Cache node_modules
        uses: actions/cache/save@v4
        with:
          path: ./src/frontend/node_modules
          key: node-modules-${{ github.sha }}

  lint:
    name: Run linter
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore node_modules
        uses: actions/cache/restore@v4
        with:
          path: ./src/frontend/node_modules
          key: node-modules-${{ github.sha }}
          fail-on-cache-miss: true

      - name: Run linter
        run: npm run lint --prefix ./src/frontend

  test:
    name: Run tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore node_modules
        uses: actions/cache/restore@v4
        with:
          path: ./src/frontend/node_modules
          key: node-modules-${{ github.sha }}
          fail-on-cache-miss: true

      - name: Run tests
        working-directory: ./src/frontend
        run: npm test
